### ISSUE TITLE
Feature request - Exclude numbers (static or variable) from a random number selection

### ISSUE THREAD

**Issue by EwenDC** [NPBruce/valkyrie#1001]
Having recently gotten Mansions of Madness for christmas, and instantly falling in love with it, I've started using Valkyrie to make my own scenario for the game. Like the sensible adult I am I've gone completely overboard with it, creating a scenario that requires tonnes of complicated logic. I read somewhere in the documentation about the use of AND and OR in event conditions (which would be an absolutely necessary lifesaver for me), only to discover that's an upcoming feature of 2.2. While enviously looking at what else 2.2 had to offer, I caught a glimpse of your new variable system. From what I can gather, variables now show up like components and have their own configuration that lets you pick a variable type other than number, as well as configure them to start pre-populated with a random starting value.

My feature request is to be able to exclude certain values from that random selection, specifically exclude values already contained within other listed variables. My use case for this feature is as follows: In my scenario there are three "entities" each with various attributes, but you're mainly trying to find out which one is the "master", with the other two being either the ally of the master, or the enemy of the master and the ally. The problem with this is I have to track this in three variables. Each variable is associated with one of the entities and lists their role as either 1 for master, 2 for ally, or 3 for enemy. The problem is if I use #rand3 to assign this, then it's entirely possible for the same value to show up multiple times. What I need across the three variables is for 1 to show up once, 2 to show up once, and 3 to show up once.

To achieve this currently, I've had to use a long string of events; A starting event that randomly picks one of three sub-events to assign 1, 2, or 3 to the first entity, then two child events of those to assign one of the remaining numbers to the second entity (then the remaining number to the third). This creates a bunch of excess event calls at scenario start, especially since I'm actually doing this whole process 3 times for three separate attributes that must be unique for each entity. If this feature request was implemented, I could tell each variable to assign a random number from 1 to 3, but not re-using the same value as the other two variables. In my scenario this would cut down the 10 events required to assign the values of each attribute to 0. That's a big improvement that's made even better when you consider how many events would be required to assign 5 variables a unique value between 1-5 (hint: 1 + 5 + (5\*4) + (5\*4\*3) + (5\*4\*3\*2)).

I don't currently have access to any images of the new variable UI to do a mockup for you, but the way I'd imagine it working is; Underneath the random value selection, you'd be able to add either variables or static numbers to a list (like you do with conditions). When choosing the random value, Valkyrie will re-draw the random number if it happens to be one of the excluded values. The only issues I can think of with this solution are:
1. With enough exclusions it might be impossible to actually pick a number. You could detect this situation with only static exclusions but with variable ones you have no idea if the variables will end up creating this situation. I think the most elegant solution is simply to only allow MaxRandomValue - 1 possible exclusions, so it's always possible to pick at least 1 number.
2. The order that these variables are instantiated and assigned a value could complicate the exclusions. I.E. If I'm assigning the random value to a variable, and I'm told to exclude the value of a variable that has not yet been assigned (due to the order of execution), how can I exclude it's value? I think the most fool-proof solution is to just ignore uninstantiated variables when excluding numbers.

Sorry for the big essay, but I hope you like my idea and will consider this feature for inclusion in 2.2 to tie in with the new variable system.

**Comment by BenRQ** [comment]
Hi ewen, you could use modulo for this.

N % 3 will return 0 1 or 2

https://en.m.wikipedia.org/wiki/Modulo_operation

**Comment by antontimmermans** [comment]
Sounds like a very interesting (replayable) scenario you are building. And very a complicated one for a first  :0. I am currently also working on a 'whodunnit&where'. in your case i would probable have created events like:
EventSelection123: person1=1, person2=2 person 3=3
EventSelection132: person1=1, person2=3 person 3=2
EventSelection213: ....
EventSelection231: ....
etc..
And then in this event box switch from Ordered (events will be called from top to bottom) to random (one of the events will be picked).
![image](https://user-images.githubusercontent.com/42072372/51023342-ffa03080-1586-11e9-8738-046f6f1c9728.png)

This way you need only 6 events (and possibly a 7th silent event': EventSelection that calls the events listed above at random).
I know its a work-around but maybe a bit simpler solution. If the number of combinations grow then this list will also explode so I can imagine that your request would be useful.

**Comment by EwenDC** [comment]
@BenRQ I'm not sure how modulo would help in my situation, unless I'm missing some basic algorithm?
Var1 = #rand3
Var2 = Var1
Var2 % 3
Var3 = Var2
Var3 % 3
Would that work? I'd think even if it did you'd only have 3 possible combinations instead of the actual 6, so not useful for my use-case.

@antontimmermans D'Oh! You are completely correct; That would reduce the number of events while being easier from a maintainability perspective. Oh well, considering I've already completed the logic the way I have I'll just leave it for somebody to screech in horror at when they decide to try editing my scenario.

**Comment by BenRQ** [comment]
If I'm correct, this should allow you to support all your cases in two events.

random=Rand()
if(random&1)
EventSelection1: person1=random %3, person2=random+1 %3, person 3=random+2 %3,
if(random&0)
EventSelection2: person1=random %3, person2=random+2 %3 person 3=random+1 %3

**Comment by EwenDC** [comment]
@BenRQ Thanks for that, I tested the logic and it works. Having two separate events is the key ingredient I didn't think of to make sure all 6 possible combinations can occur. Like I said since I've already moved past this point I'll leave my scenario with the suboptimal solution.

I still think somebody might find use in the feature I'm suggesting though, so I guess it's up to the repo managers to either add this feature to the roadmap or close the issue if they don't see value in adding it.

**Comment by NicolaZee** [comment]
Helo EwenDC 
It's great someone else is doing a murder mystery.
You might want to have a look at (or even if you're brave) 'In the Dark' which has a similar application of roles - except there are 4 instead of 3.
Role 1: Evil Dark 'Master' Druid
Role 2: Evil Dark Druid's Apprentice
Role 3: Good White 'Master' Druid 
Role 4: White Druid

When 'In the Dark' was designed I was learning Valkyrie.  It ended up with 4 lots of 4 events calling each other sequentially in a cascade of events.

BenRQ's solution is much more elegant and clever but it's a little abstract for those of us not so comfortable with maths.

I suggest approaching this problem as a set of synchronous events.  In effect the events to set the roles become like function calls.  The critical thing is if this technique is used for say 6 roles and 6 allies, the number of events needed to be added is just 4

The following code is tested and (in effect) the events EventSetRole1, EventSetRole2 and EventSetRole2 are functions (using the variable TempRole to pass in the role).  Each function is triggered by the use of the special var triggers (@SetRole1,=,1 @SetRole2,=,1 @SetRole3,=,1).  The order of the triggering is not important as long as they don't get run at the same time.  BenRQ will have a better idea than me if this might occur.

I hope the following code will give you ideas even if you don't use it to set roles. : )


[EventSetRoles]
display=false
buttons=1
event1=
operations=@SetRole1,=,1 @SetRole2,=,1 @SetRole3,=,1

[EventSetRole1]
display=false
buttons=1
event1=EventSetRoleAlly1 EventSetRoleAlly2 EventSetRoleAlly3
trigger=VarSetRole1
operations=TempRole,=,1
randomevents=true

[EventSetRole2]
display=false
buttons=1
event1=EventSetRoleAlly1 EventSetRoleAlly2 EventSetRoleAlly3
trigger=VarSetRole2
operations=TempRole,=,2
randomevents=true

[EventSetRole3]
display=false
buttons=1
event1=EventSetRoleAlly1 EventSetRoleAlly2 EventSetRoleAlly3
trigger=VarSetRole3
operations=TempRole,=,3
randomevents=true

[EventSetRoleAlly1]
display=false
buttons=0
trigger=VarSetRoleAlly1
operations=Ally1Set,=,1 Ally1Role,=,TempRole
conditions=Ally1Set,==,0

[EventSetRoleAlly2]
display=false
buttons=0
trigger=VarSetRoleAlly2
operations=Ally2Set,=,1 Ally2Role,=,TempRole
conditions=Ally2Set,==,0

[EventSetRoleAlly3]
display=false
buttons=0
trigger=VarSetRoleAlly3
operations=Ally3Set,=,1 Ally3Role,=,TempRole
conditions=Ally3Set,==,0

**Comment by NicolaZee** [comment]
Hello antontimmermans 

How about I send a few advanced examples to James and ask him if he will kindly add the examples to his excellent (and very helpful) tutorial word document?

I found it very helpful when scripting 'In the Dark'.

**Comment by BenRQ** [comment]
I don't think we should modify the way random number generation is working.
It's quite standard, and changing it could bring some confusion.

So this ticket can be closed.

@NicolaZee @antontimmermans @scrubbless , you can still work on improving the tutorial, this would clearly help a lot.
