### ISSUE TITLE
New scenario - A Little Night Music

### ISSUE THREAD

**Issue by jlederer2** [NPBruce/valkyrie#1004]
### Description of Problem or Question
Thanks for Valkyrie!  I have a new scenario to be added.  
It's located at https://github.com/jlederer2/Valkyrie/tree/master/EditorScenario12

### Valkyrie Version
2.1.5

**Comment by BenRQ** [comment]
Hi @jlederer2,
thanks for the new scenario :)

Can you please rename your scenario, and directory so it is not "EditorScenarioXX" but something closer to your scenario name ?
This name is used in stats, and it needs to fit your scenario name.

Also your scenario picture need to be a square so it fits current display format.

**Comment by jlederer2** [comment]
Done, thanks!

Jim Lederer
Open Group Distinguished IT Architect
248-345-1267
jlederer@twmi.rr.com

**Comment by chrismaliszewski** [comment]
Hi. 

I can't play this scenario as I don't have the necessary expansions but I've checked it.

So:
-(mistake) misspelling in the 'invesigators' at the beginning of the game,
-(suggestion) I'd advice to that the text 'If at first, you don't succeed' to something more elaborate and not so diminishing (I think it's the correct word :)); the same goes with some other 'fail' tests' result texts,
-(suggestion) I'm not a game developer, but I've heard that it's good if each location in a game tells a story. Therefore, I'd suggest creating something interesting for a building on the left side of the map,
-(bug) when you pick up a shotgun, there is only a 'Cancel' button. Shouldn't there be a 'Continue' instead?
-(bug) after examining the Photographic Evidence for 2>= more time, there should be text instead of nothing,
-(suggestion) I'm not sure I understand correctly '4 spaces in the tile outside the house'. Instruction is not clear enough, to me at least. 
1. Does it mean, a player can move himself 4 spaces in any direction from the house? Does that include only outside spaces or also inside ones, i.e. from one building to another? If another tile is not visible, can I uncover it without using an action? Etc. 
2. It isn't said if the moving rules apply in this situation or not. 
3. Can a player move up-to 4 spaces or 4 spaces exactly? 
4. Isn't that OP? As I mentioned in point 1., a player can move sooo far away, it can be ridiculous. 2 spaces should be enough, I think.

That's what I found. I think the scenario is good. If you put even more story into it, it can be great!

Cheers.

**Comment by jlederer2** [comment]
Wow, great feedback, thanks!  Will do!

Jim Lederer
Open Group Distinguished IT Architect
248-345-1267
jlederer@twmi.rr.com

**Comment by jlederer2** [comment]
Updated per feedback.

**Comment by scrubbless** [comment]
I've added this to the manifest and stats sheet, sorry I didn't see this sooner!

**Comment by jlederer2** [comment]
>I've added this to the manifest and stats sheet, sorry I didn't see this sooner!

@scrubbless Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
