### ISSUE TITLE
Crash in the last screen while writing feedback

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1086]
I just got a crash while playing a game.

I ran through the scenario without any issue, lost the game because an investigator died.
I got the last screen of the scenario, and then the feedback screen for rating.

I got a crash when I selected the text form, the keyboard appeared for half a second, and Valkyrie crashed.

I tried to reproduce based on the savegame, but was unable to see the issue again.

Please report if you have seen this issue too.

### Valkyrie Version
2.2.02b
Run on Android Galaxy Tab S 10
Language : French
Scenario: in places unseen

### Attach Save, Quest or Scenario
No log file (Android)

**Comment by chrismaliszewski** [comment]
Letting you know, tested other 3 scenarios with no issue sending opinions on Android device.

**Comment by BenRQ** [comment]
I'm pretty sure this is related to memory consumption.
I could find a way to free some memory once in that screen as the game is finished.

**Comment by chrismaliszewski** [comment]
I checked and Galaxy Tab S 10 has 3GB RAM. My phone has 4GB. So both have quite a big amount.

One more note which I should've mentioned before. There might be another cause of the problem. I remember having a lag when I clicked the text area before my keyboard appeared. It was like: click, freeze for ~1-2sec., a keyboard appears, back to normal. After that event, next times were ok. The situation is similar to yours, one-time problem, the rest of the times ok. 

But, yes, it's always good to clean memory when it's not used - I've learned that hard.

**Comment by redwolf2** [comment]
A short delay is ok and could be Androids low memory killer freeing up an app. In worse scenario the memory killer might even kill your foreground app.

https://www.youtube.com/watch?v=w7K0jio8afM

Crashes might also be a result of a fatal, uncatched error. It is also a good idea to dispose objects directly after use instead of letting the garbage collector do that work. 

I'd found and fixed such issues in the importer where FileStreams were left open until the garbage collector was kicking in. On windows, even though not ideal, this wasn't a problem. On Android the memory was stacking up until it crashed.

**Comment by BenRQ** [comment]
It would be great to use a system like Crashlytics, or anything else that would report crash automatically.
I will put this in my top priority list, I think this is a must have.

**Comment by BenRQ** [comment]
Crashlytics has been added to 2.3 version.
This issue will be closed, and re-open if crashlytics reports confirm it still exists.
