### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by Gruszkomir** [NPBruce/valkyrie#1117]
New scenario.  Only in polish for now

https://github.com/Gruszkomir/Scenariusze/tree/master/MiastoweMgle

**Comment by scrubbless** [comment]
Hi @Gruszkomir 
Thanks for submitting, but we need to fix a couple of things before I can publish this.

The Manifest for Valkyrie will not accept spaces (%20), so could you remove the space in the scenarios Repository. Also could you rename the scenario, it appears to have the default for polish. With a default name it will not show up in the statistics and you will not be able to see feedback or have your scenario rated.

![image](https://user-images.githubusercontent.com/32058089/54673603-7eb76500-4af2-11e9-9fa7-20230437efc0.png)

You can change the scenario by renaming the scenario folder in the Editor directory:

%appdata%Valkyrie\MoM\Editor\
![image](https://user-images.githubusercontent.com/32058089/54673782-e66db000-4af2-11e9-9490-38ecd9bac81e.png)

**Comment by chrismaliszewski** [comment]
I'll write some "issues". I don't have physical expansions so I only tested the scenario in the app. 

1. Before even the scenario starts, you click Continue twice and after that there is nothing. I mean, it isn't clear to click again to continue. It'd be good if there was a "Start" button or something like that.
2. (I'm Polish) You have mistakes in the text, bad interpunction, misspellings etc.. 
3. When a phase changes, it'd be nice if they have a screen indicating it. 
4. Should some buttons be blue?
5. After you open the bottom door on the second screen and a new tile appear, a wall should be placed immediately, not after you open another door!  
6. I find the test at the school entrance BAD. No matter how many success dice you through, you always evade and never get the shotgun. Is it possible to get it? Why the blades are there? Blades in the walls of a school? That also doesn't make sense. 
7. Why there is only one entrance to the Printing Press if there are two doors? Either add an extra explore token or coved another door with a wall.
8. It is possible to fire the event of the appearing of the kid fires twice. Once if you go through school, the second time if you go through the secret entrance. Create a trigger preventing the behaviour.

I haven't been following the plot much but from what I followed it seems nice :).

**Comment by scrubbless** [comment]
> When a phase changes, it'd be nice if they have a screen indicating it.

This is done by Valkyrie. It doesn't appear when you "save and test" bit if you run the scenario from offline mode you'll see investigator and mythos splash screens.

**Comment by chrismaliszewski** [comment]
I see. Didn't know. I'm not a creator :). Thanks, scrubbless.

**Comment by Gruszkomir** [comment]
Hello, i make a update :) I think I corrected most of the errors

**Comment by scrubbless** [comment]
Hi @Gruszkomir

I've added the scenario to the manifest but it doesn't appear to be listing. 

I suspect the . (Full stop) in your repo name may be causing an issue.

@benrq can you check if you can see an error in Valkyrie?

**Comment by BenRQ** [comment]
The scenario appears (maybe check your filter language?), but download doesn't work.

@Gruszkomir , you should use the same filename between the .ini and the .valkyrie, otherwise the app can't find the file.

You should not use the directory name, or filename to track version number.
To track the version, I recommend to use the scenario name like Scrubbless does.
Because if you change the directory or filename again, we will have to change the path again and you won't be autonomous to manage your update.

So: 
1) rename your directory MiastoweMgle
2) Rename the Valkyrie file MiastoweMgle
3) Scrubbless update the path when it's done, and it should work :)

**Comment by scrubbless** [comment]
Yeh I just notice that it appeared:
![image](https://user-images.githubusercontent.com/32058089/54743526-4419ff00-4bbc-11e9-80a1-77cbba938131.png)

However it won't download.

You should rename your un-packaged scenario and repo name (remove the full stop to be safe) then re-package the scenario from inside valkyrie (tools, create package).

**Comment by Gruszkomir** [comment]
I have a problem. when I create a package, I'm not able to open it by valkyrie. The scenario works only when I unpack it manually to the editor folder

**Comment by scrubbless** [comment]
When you create the package it exports it to a folder on your desktop. If you drop that folder into %appdata%\valkyrie\mom\editor directory you will see it in offline mode.

**Comment by Gruszkomir** [comment]
Ok i update the link https://github.com/Gruszkomir/Scenariusze/tree/master/MiastoweMgle

I also make i this video to show my problem 
https://www.youtube.com/watch?v=nW68eP3pp-g

**Comment by scrubbless** [comment]
I have updated the scenario with the new link.

In regards to your video.
I think I understand the problem, I don't believe you can just drop files into the "Downloads" folder in Valkyrie, since it only contains .valkyrie files of scenarios that you have downloaded. 

If you copied a scenario in there you would need to reference it in the manifest.ini.
Here is what mine looks like:
![image](https://user-images.githubusercontent.com/32058089/54750855-05db0a80-4bd1-11e9-9fa3-3ad0233e6f88.png)

`[StrainOnReality]
format=10
hidden=False
type=MoM
defaultlanguage=English
difficulty=0.6
lengthmin=210
lengthmax=270
image=logo.png
version=24-96-9B-28-6B-33-8B-B5-16-DE-38-F6-8D-CD-DE-46-B2-52-DA-DE-8A-48-5A-F0-D1-66-A6-7E-B1-93-58-9E
name.English=A Strain on Reality (v1.7)
synopsys.English=You have heard rumours of some strange goings on at the Rowley Asylum, run by Dr Joyce Little.
authors_short.English=Scrubbless

[BirdsShop]
format=9
hidden=False
type=MoM
defaultlanguage=Spanish
difficulty=1
lengthmin=60
lengthmax=150
image=whi.jpg
version=B7-EC-38-5D-82-B0-BD-B8-DF-6F-66-40-B4-EA-45-7B-5E-9D-7E-D9-EF-B1-82-DB-9D-2B-36-07-55-31-B0-EF
name.Spanish=En la pajarería a las 22.30h
name.French=La volière à 22h30
name.English=22.30h at the bird shop
authors_short.Spanish=Miss Fernwood & EtiCarasoft
authors_short.English=Miss Fernwood and EtiCarasoft
authors_short.French=Miss Fernwood et EtiCarasoft
synopsys.Spanish=La familia Gordon se ha puesto en contacto contigo para que encuentras a su hija, Felicia.Lleva unos días desaparecida.
synopsys.French=La famille Gordon vous a contacté pour retrouver leur fille, Felicia. Elle a disparu depuis quelques jours.
synopsys.English=The Gordon family has contacted you to find their daughter, Felicia. She has been missing for a few days.

[VuelvexNavidad]
format=10
hidden=False
type=MoM
defaultlanguage=Spanish
packs=MoM1EM MoM1ET
difficulty=0.65
lengthmin=90
lengthmax=120
image=bolamonster.jpg
version=46-91-0A-4F-CD-83-EB-D1-15-30-71-EA-57-23-29-AE-58-CF-BC-06-FC-93-CA-6F-03-47-5F-A2-FD-E2-DE-00
name.Spanish=Vuelve por Navidad

[ALittleNightMusic]
format=9
hidden=False
type=MoM
defaultlanguage=English
packs=CotWT CotWM
difficulty=0.6
lengthmin=120
lengthmax=180
image=Forest.jpg
version=1E-5D-EA-C6-51-1E-79-BF-5C-11-64-C3-C5-91-2A-23-CE-0C-FF-D4-37-DD-3F-DC-0E-98-41-AE-76-98-A8-37
name.English=A Little Night Music

[EditorScenario3]
format=9
hidden=False
type=MoM
defaultlanguage=English
minhero=3
difficulty=0.5
lengthmin=120
lengthmax=180
image=basement.png
version=1A-B9-77-39-C8-92-71-AF-17-2D-F4-EC-54-70-17-BC-6D-7B-F3-70-EC-F7-D3-EE-72-78-C1-80-08-15-9C-66
name.English=Amnesia

[Stressandstrain]
format=10
hidden=False
type=MoM
defaultlanguage=English
packs=MoM1ET MoM1EM
maxhero=6
difficulty=0.6
lengthmin=120
lengthmax=210
image=splash.png
version=E7-49-EF-EA-70-F8-CC-D8-21-53-ED-90-67-D9-CE-EE-23-B4-A3-19-25-15-93-77-90-4E-C5-CF-48-4F-2A-70
name.English=Stress and Strain (V3.4.2)
name.Polish=Stres i wysiłek (v3)
synopsys.English=What you expect to be a normal journey, turns out to be more traumatic than you could have imagined.
authors_short.English=Scrubbless

[Demo]
format=10
hidden=False
type=MoM
defaultlanguage=English
minhero=1
maxhero=4
difficulty=0.8
lengthmin=120
lengthmax=150
image=logo.png
version=F6-C4-DD-A4-AC-D9-E7-D1-9B-4E-17-9E-0E-31-1A-10-06-A3-E8-C0-76-E1-C6-90-5C-5B-B5-B2-86-65-8E-4C
name.English=Valkyrie Examples and Demos

[UnaTristeVerità2]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=MoM1EI MoM1EM MoM1ET RN
minhero=1
difficulty=0.8
lengthmin=60
lengthmax=90
image=inssmouth_small_john_dunn2.jpg
version=20-A7-C4-49-98-27-A8-71-4F-14-BE-A5-C3-11-AE-C6-97-E2-96-E9-26-62-71-64-2D-66-82-77-3F-B9-BE-C8
name.Italian=Una Triste Verità - Seconda Parte -

[UnaTristeVerità0]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
minhero=1
maxhero=3
difficulty=0.2
lengthmin=20
lengthmax=40
image=lettera.jpg
version=69-E1-3F-E2-26-4A-7E-43-33-5A-DD-17-13-7D-C7-F6-4D-AB-41-42-BF-C5-58-C6-94-05-BC-34-1C-87-BD-FC
name.Italian=Una Triste Verità - prologo -

[UnaTristeVerità1]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=RN MoM1EI MoM1EM MoM1ET
minhero=1
difficulty=0.8
lengthmin=60
lengthmax=90
image=IMG_0083(1).JPG
version=D6-D1-F6-30-CA-23-53-A0-28-95-55-BB-F7-E0-76-01-1B-17-96-B9-72-88-E1-1B-11-EC-26-DE-92-2F-AF-F8
name.Italian=Una Triste Verità - Prima parte -

[UnaTristeVerità3]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=RN MoM1EI MoM1EM MoM1ET
minhero=1
difficulty=0.8
lengthmin=30
lengthmax=45
image=Innsmouth (4).JPG
version=5B-E1-86-C3-08-8A-56-D3-5F-49-BD-53-42-A1-28-05-A2-61-98-F0-B3-49-6B-0F-32-5B-09-7C-07-81-7A-29
name.Italian=Una Triste Verità - Epilogo -

[La_Mascarada]
format=10
hidden=False
type=MoM
defaultlanguage=Spanish
packs=SoA
difficulty=0.6
lengthmin=120
lengthmax=180
image=mascara.jpg
version=EA-17-C7-4E-61-95-61-21-9B-BF-8B-94-55-2B-9D-80-3B-9F-85-8A-9A-0D-C7-04-BE-DC-18-46-F4-D1-D3-3C
name.Spanish=La Mascarada

[La_Maledizione_di_Cthulhu]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=SM RN MoM1EI MoM1EM MoM1ET FAT FAM FAI CotWT CotWM CotWI
difficulty=0.6
lengthmin=45
lengthmax=60
image=Cthulhu.jpg
version=41-36-9F-98-01-7B-1C-86-4C-73-81-E3-C4-75-7B-22-DB-63-B2-49-A0-35-31-69-FE-EC-4E-11-AE-56-65-54
name.Italian=La Maledizione di Cthulhu

[EditorEscenario1]
format=10
hidden=False
type=MoM
defaultlanguage=Spanish
difficulty=0.8
lengthmin=90
lengthmax=260
version=55-9D-A5-6E-BD-D1-0F-DE-49-3F-E0-BF-5C-A9-4A-36-62-70-0F-01-8B-32-AB-D9-23-BF-02-CE-B5-AD-2A-E6
name.Spanish=Las mujeres desaparecidas

[Il_Manufatto_Conteso-Competitivo]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
maxhero=6
difficulty=0.8
lengthmin=30
lengthmax=60
image=fuga.JPG
version=39-A3-3F-76-77-A2-EB-AC-02-29-3B-DF-9E-FA-D4-AF-7C-38-96-E3-DC-D5-10-A1-E8-39-51-89-96-FA-C6-A0
name.Italian=Il Manufatto conteso

[Il_Mistero_della_Villa_Parcival]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=BtT MoM1ET MoM1EM MoM1EI RN
minhero=3
difficulty=0.8
lengthmin=90
lengthmax=120
image=Image_3_000036.jpg
version=88-BE-71-4E-A0-F1-6D-04-EF-C0-65-16-7C-00-9C-41-D9-91-71-D1-A8-67-C3-44-75-D3-E3-81-B7-0C-70-2E
name.Italian=Il mistero della Villa Parcival

[Rapimento]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=RN MoM1EI MoM1EM MoM1ET BtT
difficulty=1
lengthmin=90
lengthmax=120
image=Haunted+House+HD+Wallpapers9.jpg
version=26-90-CA-4C-B2-A7-56-DF-C3-44-B5-F3-4C-F3-C4-EF-CE-FC-63-B5-D8-0C-DD-42-DD-E8-D7-C8-B3-7E-17-0C
name.Italian=Il Rapimento

[La_Casa_Infestata]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
difficulty=0.2
lengthmin=60
lengthmax=90
image=casa interno.jpg
version=6B-58-E1-F8-61-CD-97-B4-23-66-26-F2-E3-43-9A-43-FF-C8-40-81-25-BE-93-F4-B8-47-94-77-7E-69-ED-C0
name.Italian=La Casa Infestata

[La_Follia_di_Arkham]
format=10
hidden=False
type=MoM
defaultlanguage=Italian
packs=RN SM BtT SoA MoM1EI MoM1EM MoM1ET FAI FAM FAT CotWI CotWM CotWT
minhero=1
maxhero=4
difficulty=1
lengthmin=300
lengthmax=360
image=Arkham giorno.JPG
version=33-99-E1-63-EE-DD-58-5C-51-37-C5-0F-67-C7-D0-38-D9-ED-C4-F0-92-6B-CF-4F-B5-F9-15-74-E4-B8-54-E9
name.Italian=La Follia di Arkham
`

This is a lot of work that you won't really need to work about.

The package (folder) that you have created. Are you just uploading that directly to GitHub?

**Comment by scrubbless** [comment]
Could you do the following please?

Create a new Repo maybe call it "PublishedScenarios" (this is how I have done it).

Then Open Valkyrie, Open the Editor, click Tool and click "Create Package".

The folder appears on your desktop, then upload that entire folder into your "PublishedScenarios" folder (I use github desktop, so would just drag the folder into my "PublishedScenarios" folder, which is a clone of that repo).

There is a second of the guide that covers this (sorry that its only in english and spanish!):

English:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.b0b9k5j2yj4u

Spanish:
https://docs.google.com/document/d/1yogKLaSEFFZvnJ0VdVDMKzohv2k0XPsHlVxW30qha8g/edit#heading=h.23bsikj71dw3 
(jump link is not working, this link is to the topic before, just scroll down)

**Comment by scrubbless** [comment]
This is how I do it:

I have a PublishedScenarios repo on my github:
![image](https://user-images.githubusercontent.com/32058089/54751370-ae3d9e80-4bd2-11e9-8968-5c4c78da08be.png)

In GitHub Desktop I have cloned this repo to my desktop:
![image](https://user-images.githubusercontent.com/32058089/54751427-d75e2f00-4bd2-11e9-8187-8139df868a6c.png)

Here you can see the contents are in Sync:
![image](https://user-images.githubusercontent.com/32058089/54751434-e218c400-4bd2-11e9-8611-06f17841de64.png)

I create a new package:
![image](https://user-images.githubusercontent.com/32058089/54751499-17bdad00-4bd3-11e9-91b6-dfd52161d47d.png)

The scenario is generated and put onto the desktop and I just drag it to the PublishedScenarios folder (which is the local version of my online repo):
![image](https://user-images.githubusercontent.com/32058089/54751589-4f2c5980-4bd3-11e9-9ed5-e3ce9c0cf2a4.png)

The new scenario appears in GitHub Desktop:
![image](https://user-images.githubusercontent.com/32058089/54751629-73883600-4bd3-11e9-92f3-a5013e4e1998.png)

I can then commit this and push it to my online repo:
![image](https://user-images.githubusercontent.com/32058089/54751667-9286c800-4bd3-11e9-815b-e862345e80a8.png)

**Comment by Gruszkomir** [comment]
> No need to do anything I just said, your new link is working:

You're right ! It's working now. Thanks for your patience ! This is my first scenario, where I practiced how valkyrie works. I have more complicated scenarios in preparation,
I just have to play "live"

**Comment by scrubbless** [comment]
Thanks @Gruszkomir 
We got there in the end! It should be easy for your next one!

I would encourage you to look into GitHub desktop, it is really handy.

For example, you can create a repo for "WorkInProgress" scenarios and clone it to 
%appdata%\Valkyrie\MoM\Editor\

When you create a new scenario just move it into the "WorkInProgress" folder (in the UNC path above) and it will still be visible in the Valkyrie Editor. When you make changes and hit save, you will see the changes appear in GitHub Deskop and you can commit them to your online repo. This will give you version control and the ability to clone your code to as many machines as you like.

I have this setup on three PC's, so that I can work on my scenarios and keep all of the code in sync.

Here is an example:
![image](https://user-images.githubusercontent.com/32058089/54752591-96681980-4bd6-11e9-867b-f6b6e7f97d8c.png)

![image](https://user-images.githubusercontent.com/32058089/54752613-ae3f9d80-4bd6-11e9-979d-c3e387371366.png)
