### ISSUE TITLE
Enhancement:Return to calling event

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1137]
### Question
When placing a tile that contains tokens or items with a visibility that depends on another event, the programming can become quite complicated or elaborate. This conditional placement of tokens, persons and items makes a scenario feel more alive. The investigators will feel that their actions progress the story.

_Example: You place the library tile , add a door and an explore token. Then, place the search token for the book only when you know what to look for (after speaking with someone), and place a person token only if the room is revealed in round 3 and 4._

This can be solved with the 'Loop-tactic'. An event that calls conditional placement events that trigger the loop event again until it has reached the number of items to place. 
Or you can use the 'funnel-tactic' where each conditional placement item calls all next placement events (minus 1). Example:
PlaceTile Calls PlaceItem1
PlaceItem1 Calls ConditionallyPlaceItem2, ConditionallyPlaceItem3, ConditionallyPlaceItem4
ConditionallyPlaceItem2 Calls ConditionallyPlaceItem3, ConditionallyPlaceItem4
ConditionallyPlaceItem3 Calls ConditionallyPlaceItem4
Both tactics are quite some work to get right, or may be considered too complicated . I  suspect that this is why some scenarios (with good stories) have quite basic placement: Dump all tokens on a tile at once with a simple description, leaving the players guessing what to add.

To stimulate this more lively behavior of a scenario, it maybe an idea to add a feature that may simplify the programming of this conditional placement. There for I was thinking about a 'return-to caller' event. Next to conditional placement simplification, it will also make programming (and re-use of events) cleaner and easier if an event could return to calling event.
When a called event returns to its caller, the caller executes the next listed event.

The example above would simply look like: 
PlaceTile Calls PlaceItem1, ConditionallyPlaceItem2, ConditionallyPlaceItem3, ConditionallyPlaceItem4
Each placement event would then simply call 'Return' after it has placed the item
Now you need also to create the placement event once. It can be called when the tile is placed and the item should be added. Or when a dialogue gives a hint about the item and you want to place the item on the already reveled tile.

I can totally imagine that this is quite complicate to program in Valkyrie. That is why I put this as a question. Would it make sense to have such a function? **Your Opinion Wanted**

### Valkyrie Version
Any

**Comment by chrismaliszewski** [comment]
I think a non-creator opinion may also be interesting so I'll write my opinion after reading @scrubbless's tutorial. 

@antontimmermans, isn't what you write in your example already working in Valkyrie? You can create a single event calling others one after another while inside those you can create test conditions to determine if the event should do its job, can't you? Correct me if I'm right. If the answer is 'yes', the conditional placement is just a matter of creating events with test conditions properly resulting in events being reusable. 
To some extent, I agree with you that creating events floating "in the air" waiting to fire if conditions are met would be great. Unfortunately, I don't think it's the way to follow! Imaging tens of events like that just waiting and using resources in the meantime; it could create big performance issues (memory/CPU)! That's not the way you create code; your code should be reusable. If you create events correctly in the first place, you can use them as many times in different places as you want when they are needed, and only then. 

Let's take your example with the library and the book. You need two variables:
1. iIsTheLibraryTileOnBoard - 0 = no, 1 = yes,
2. iIsTheBooksLocationKnown - 0 = no, 1 = yes.

Then you create events:
1. one which puts the tile on board and sets iIsTheLibraryTileOnBoard to 1,
2. one which puts the book on board but only if both iIsTheLibraryTileOnBoard and iIsTheBooksLocationKnown are = 1, 
3. one which fires 1. and 2. when entering the library,
4. one which sets iIsTheBooksLocationKnown to 1,
5. one which is a dialogue about the book which fires 4. and then 2. 

I'm not sure what's the order of assigning variable's value and firing an event but if an assignment is done first and then firing events, the above list can be shortened to 3 events: 2. stays as it's, 1. and 3. are merged as well as 4. and 5. merged. 

The process requires deep thinking about your scenario and some "programming" skills/way of thinking so more work. Perhaps that's why not many people do such a thing. 

Personally, I think the biggest problem with creating more complex things in Valkyrie's Editor is the latter's design. It is very rustic and, as a result, it has a little bit hard point of entry to know what and how to do sth to achieve some desired goals, i.e. 'Person Token with Several questions' section of the tutorial is a good example. 
Although I am a programmer and I code using words, I really like the idea of automatic creation of code using flow-charts, i.e. as it's done in LabVIEW. Therefore, I ideally imagine the creation of scenarios being done this way:
![image](https://blogs.unity3d.com/wp-content/uploads/2018/03/Bolt5.gif)
I mean, the code which is created right now in the editor would be represented in a more user-friendly way which would speed-up and make the process of creating scenarios easier to see and understand. I'd be doable but it'd require setting most of the things created up-to this moment up-side-down. 
The latter is just a dream or an inspiration for another time.

**Comment by NPBruce** [comment]
There is a way to do return to caller with variable triggers:
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#trigger

However there are some limitations (read the description) and I am not convinced this will be any easier that the existing methods you describe (I expect it will be worse as it will be harder to follow what is happening).

Ultimately the scenario you describe has a large number of permutations of what can occur, and these permutations will need to be accounted for by the scenario author, that isn't something that can be avoided.

I would also call into question @chrismaliszewski assertion regarding programming resources, which at this level are trivial compared to the rendering of the scene. Additionally, they don't have to be always running, the way that the existing var triggers work has no overhead unless a var trigger is set.

A visual representation would certainly help, and I don't think this is incompatible with the existing architecture, you could create such a chart automatically without changing the way events work at all.

**Comment by antontimmermans** [comment]
@NPBruce I am aware of the var-trigger events, but I had no idea it could be used like this. Just to be sure, Do you mean you could make this structure?:

```
[EventPlacePersonA]
; PersonA only appears in the library in round 3&4 and only if the library is revealed;
trigger=VarPlacePersonA
add=PersonToken
Operations=PersonA=2
testcondions=#round >=3 && #round <= 4 && TileRevealed == 1 && PersonA !=2

[EventPlaceBook]
; Book will be placed only when it is not placed already, Vissible And library tile placed;
trigger=VarPlaceBook
Operations=BookVisible=2
testcondions=BookVisible == 1 && TileRevealed == 1

[EventPlaceTile]
add=LibraryTile
buttons=1
event1=
Operations=TileRevealed=1, @PlacePersonA=1, @PlaceBook=1

[EventDialoguePersonB]
Operations=BookVisible=1, @PlaceBook=1

[StartRound]
Operations=@PlacePersonA=1
```

**Comment by NPBruce** [comment]
That's the idea. Note that there is no requirement for the order that the events will execute when setting multiple triggers in the same event (one of the reasons I don't think this is a great idea).

**Comment by antontimmermans** [comment]
I think I understand the possible mess or unpredictable behavior it can create... therefor the 'return to caller' idea :)

**Comment by NPBruce** [comment]
How is that idea different though? Events triggered by vars do return to the caller.

**Comment by scrubbless** [comment]
Is there an action here or can we close of this issue @antontimmermans

**Comment by antontimmermans** [comment]
I didn't have the time yet to check if the behavior is indeed as Bruce describes but i guess it will work. I'll close the issue.
