### ISSUE TITLE
Bug: SE list not being compared with the actual files on disk 

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1139]
I wanted to test @antontimmermans' scenario so I moved the old ChapelDownManor's valkyrie file from %appdata%Download. I opened the app and surprisingly noticed the scenario still being on the SE list. After you click on it, you can only see the black screen and ALT+F4 is the only thing you can do.

I understand that 'you should do everything in the app' way of thinking but say 'no!' to this kind of things :).

I'm using the newest version of Valkyrie app.

**Comment by chrismaliszewski** [comment]
Another associated issue:
1. SE list
![image](https://user-images.githubusercontent.com/7532602/55785610-0b7e8e80-5ab3-11e9-8089-69593ac6d532.png)
2. Actual scenario after opening it
![image](https://user-images.githubusercontent.com/7532602/55785631-120d0600-5ab3-11e9-8d20-c02b4958208d.png)

**Comment by chrismaliszewski** [comment]
My mistake. I forgot how the online list is created and that I should've checked offline one.

**Comment by scrubbless** [comment]
No worries @chrismaliszewski 

The SE seems to use a manifest file, so it can be a bit odd if you manually add files into folders. 

For example I was "sure" that you could drop a scenario package into Downloads in the past and see the scenario in the "New Scenario" section. But since the SE, you can't just drop a scenario in that folder as it will not list in offline mode.

The work around I found was to unzip the scenario and drop it in the editor folder.

I'm sure there is a way to drop the scenario in the downloads folder and modify the manifest, but I am not sure what to do there.
