### ISSUE TITLE
New Scenario Spanish  El Culto de Cthulhu

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#1149]
### Description of Problem or Question

Uploaded new scenario. El Culto de Cthlhu

Language Spanish

https://github.com/newusergettingnuts/ElCultodeCthlhu

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by chrismaliszewski** [comment]
Hi. I don't speak Spanish so I've just checked the scenario generally.

1. I'm wondering why there is only one monster/there is any monster at all if there is only one? It'd be good to either put more of them there or none to be consistent, IMO. 
2. **Important** Change the number of numbers displayed in the final riddle, otherwise, if a random number will be 9, the riddle will be unsolvable as it's impossible to click it:
![image](https://user-images.githubusercontent.com/7532602/56621752-cf862480-6681-11e9-8b23-4343d9ed2579.png). The general issue has been mentioned [here](https://github.com/NPBruce/valkyrie/issues/1105).

**Comment by newusergettingnuts** [comment]
hi, chris thanks. 
 
1-there are many more than one monster.
2-i started the issue you mention and the scenario works fine as it is.

please if possible deleate your previous post, it spoils an important part for players.

Comments in private if possible.

**Comment by chrismaliszewski** [comment]
Ok, I deleted the post although I don't think I spoiled anything. 
I'm not sure to write comments in private so I'll send you a private mail on GitHub.

**Comment by scrubbless** [comment]
I've added the scenario to the manifest, once its updated I'll close this issue.

I am a bit behind on the stats spreadsheet, I'll add the two new scenarios to it when I get some spare time.

**Comment by newusergettingnuts** [comment]
> I've added the scenario to the manifest, once its updated I'll close this issue.
> 
> I am a bit behind on the stats spreadsheet, I'll add the two new scenarios to it when I get some spare time.

thanks scrubbles dont worry once someone plays this one i will check the rawdata and add it to the spreadsheet as i did with Massachussetts.

**Comment by scrubbless** [comment]
I have another to add anyway, so will do it I'f I get there before you :D

Its showing in the scenarios list now, closing case

**Comment by newusergettingnuts** [comment]
Version 2.0 uploaded (many thanks to all the comments received)
