### ISSUE TITLE
Can I get access to comment on reviews?  Also, review comments error

### ISSUE THREAD

**Issue by jlederer2** [NPBruce/valkyrie#1197]
I'd like to be able to comment on reviews for my scenarios (e.g. A Little Night Music).

Also, when I filter the reviews page for my scenario, I see that there are responses to reviews for a couple of reviews...but they were not entered by me, and perhaps are for a different scenario entirely!

Thanks!

**Comment by scrubbless** [comment]
Hello, not a problem I can give you access.

Can you let me know your gmail account. If you sont want to post it here, PM me on BGG.

As for responses, I need to re move them. Its not a good medium to respond due to the way google sheets sorting randomly breaks.

The reason you have responses next to yours is someone else responded to a comment and then the sheet has been sorted and the sort function didnt include a column.

I have no idea why it does this but seems to be a bug with google sheets filters.

**Comment by jlederer2** [comment]
jlederer2@gmail.com

Thanks!

Jim Lederer
248-482-3668

**Comment by scrubbless** [comment]
Added permissions
