### ISSUE TITLE
Support Path of the Serpent (MAD28)

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1204]
### Description of Problem or Question
Path of the Serpent is a new expansion for Mansions Of Madness.

https://www.fantasyflightgames.com/en/news/2019/6/24/path-of-the-serpent/

**Comment by NPBruce** [comment]
Changes:

version to 1.8.0

Font Updated (ICON_PRODUCT_MAD28)

Audio added:
MetalRotate_01
MetalRotate_02
MetalRotate_03
StoneRotate_01
StoneRotate_02

Images added:
ArtSnake_3x3
artStrangledbyVines_3x3
Background
Investigator images
Item images
MAD28
Metal_Center
Metal_Inner
Metal_Middle
Metal_Outer
monster images
scanario_ltD
scenario_LotST
scenario_TJA
Spells
Stone_Center
Stone_Inner
Stone_Middle
Stone_Outer
Tiles

**Comment by scrubbless** [comment]
Hi @NPBruce / @redwolf2 

I am hoping to get The Path of thew Serpent in the next couple of weeks, is there anything you need to help with the integration? I can't/have not had the time to get my head around the code of Valkyrie (its been 20 years since I did C# and I wasn't that good at it back then! :D), but if there is anything else I can do to help. Please let me know, would be great to start using some of that content in Scenarios 😁

**Comment by redwolf2** [comment]
I am on it

**Comment by redwolf2** [comment]
It is done.

**Comment by scrubbless** [comment]
Awesome news, well done!

**Comment by keros17** [comment]
Also I have told to @scrubbless that if there are any possibility to translate the Valkyrie app into other languages, for example, catalan (I'm from Catalonia and maybe some people will be glad of having it in that language, at least the app not, for the moment, the scenarios) I will interested on helping.

@NPBruce @redwolf2 

Thanks ^^

**Comment by holgaard** [comment]
Will there be an update to the MAD Garamond Pro font, so that the PoS icon is included?

**Comment by scrubbless** [comment]
I believe that's included in the alpha currently, so will come through to live I should think.

**Comment by redwolf2** [comment]
Support was added in v2.4.07
