### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by Rygal1984** [NPBruce/valkyrie#1231]
https://github.com/Rygal1984/Casa-de-las-sirenas

**Comment by scrubbless** [comment]
Hi @Rygal1984 

I can't link your scenario because it has the default folder name = "EditorEscenario1".

Could you please edit the folder name of your scenario in %appdata%\valkyrie\MoM\Editor

The new name cannot contain any spaces.

Then package the scenario and upload it to github again.

Once it has a unique name I can link it for download in Valkyrie.

**Comment by Rygal1984** [comment]
https://github.com/Rygal1984/CasadelasSirenas0

**Comment by scrubbless** [comment]
Great thanks, added. It should show in the list within the hour.

**Comment by Rygal1984** [comment]
It's the first one I do, I hope you like it ^^

**Comment by scrubbless** [comment]
It is showing, however with SoA and BtT selected the scenario appears to have a few bugs right from the offset.

I cant speak for the text as I dont speak the language, but the top right Explore does not trigger anything, no text. The bottomed left Explore automatically opens the door, the top left Explore doesnt require an action to open.

I would recommending getting some play testers to try your scenario and give feedback.
