### ISSUE TITLE
Footsteps in the Dark in Portuguese

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1288]
Creating this issue to help BGG User _GwanGwanish_ to publish the Localization file for **Footsteps in the Dark**.

File to be added: 
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/4662223/Localization.Portuguese.txt)

Simplified steps:
1. Coopy the file above to %appdata%Valkyrie\MoM\Editor\<ScenarioName>
2. Edit quest.ini file and include "Localization.Portuguese.txt" below [QuestText]
3. Open Valkyrie > Scenario Editor > Your Scenario. Click Tools and Create Package. The new package will now contain the additional language.
4. Copy these files to your online repository (copy to local repository and commit changes if you are using GitHub).

Longer explanation available here: https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.ka65mn7ohsbw

**Comment by scrubbless** [comment]
@GwanGwanish a translation for your scenario here :)

**Comment by GwanGwanish** [comment]
Taking a stab at this today.

**Comment by GwanGwanish** [comment]
I think I did that right. Will test it once it the updated scenario posts to Valkyrie. Thanks @Revokee Revokee!

**Comment by scrubbless** [comment]
Hi @GwanGwanish 
I've just checked your update and noticed you added the translation to the repo, rather than to your scenario and repackaging.
![Screenshot_20200601-195936_Chrome](https://user-images.githubusercontent.com/32058089/83443993-98687200-a442-11ea-9820-189f7b1cf5c1.jpg)

You will need to drop the translated localisation file in %appdata%\valkyrie\MoM\Editor\(your scenario)\

Then edit the quest.ini and add the filename (Localisation.Portuguese.txt) - this will be just under where is says Localisation.English.txt.

Once done open Valkyrie, then your scenario in the editor. From the tools menu 'Create a package' then upload that to your GitHub repository overwriting the old scenario.

Page 235 - Adding a translation file, should help explain the process:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit?usp=drivesdk

**Comment by GwanGwanish** [comment]
K. Think I got it this time!

**Comment by GwanGwanish** [comment]
Hmm... I added the translation localisization file to the scenario folder,
edited the quest.ini to include it beneath the english.txt, saved in
Valkyrie, repackaged and uploaded to Github. Github reflects a new version
number, but I don't see the Portuguese flag.

I'll take another stab at it tomorrow.

**Comment by scrubbless** [comment]
Hi GwanGwanish, 

The localisation file is showing but it doesn't appear to be added to the quest.ini in your package:
![image](https://user-images.githubusercontent.com/32058089/83503357-dacd9580-a4ba-11ea-837b-854123c24a8a.png)

I've corrected this and created the package here, if its easier:
[EditorFootsteps.zip](https://github.com/NPBruce/valkyrie/files/4716177/EditorFootsteps.zip)

**Comment by GwanGwanish** [comment]
Hmmm.. weird. I added it to the Quest ini, but maybe it was the wrong
scenario folder. Sort of had to guess, because I no longer had the original
scenario folder. Had to redownload it from Valkyrie, make a copy, edit,
save, repackage, etc.

I'll try the zip. Thanks.

**Comment by Revokee** [comment]
@GwanGwanish I believe it worked - I can see the map in Portuguese now.

Thanks for your support!

@scrubbless I belive that we can close this issue.

**Comment by GwanGwanish** [comment]
Excellent. Thanks everyone! sorry for the delay. Been a little crazy here
in NY.

**Comment by scrubbless** [comment]
Awesome, glad it's sorted!
