### ISSUE TITLE
[Bug] Migo and Serpent Person Issues

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1326]
A review left on my scenario, Search for a Friend, mentioned that the Migo monster had no Evade or Horror effects.  I did a quick run through and found that this was actually the case.

I also noticed that the Serpent Person monster won't allow me to attack with a Spell when I run through a scenario that I'm working on.

Valkyrie Version 2.4.09

 - Windows 10

**Comment by redwolf2** [comment]
Feathered Person works for me:

![grafik](https://user-images.githubusercontent.com/4141621/86855664-18759d80-c0bb-11ea-9b77-64add4a80361.png)

![grafik](https://user-images.githubusercontent.com/4141621/86855677-1e6b7e80-c0bb-11ea-9a49-730088fbc615.png)

**Comment by antontimmermans** [comment]
this ticket has overlap with #1157

**Comment by mayjak** [comment]
This is actually interesting. As it is now we only support a few attacks against the snake person. What the FFG app does is it treats the snake person as a humanoid, except for the attacks that mention legs in the description, which are obviously replaced by a snake tail in the descriptions.

I think the easiest fix for now is to add the attack mappings to the .ini file. That's because it's the only case that modify another "trait" attacks. I'll have a fix today.

The migo is a bit different case I think, but I'll check that as well.

**Comment by mayjak** [comment]
So for the migo it seems there's a very simple string casing issue in horrors.ini and evade.ini ("Migo" instead of "MiGo").
