### ISSUE TITLE
New Scenario: INSANE

### ISSUE THREAD

**Issue by SylvyaVega** [NPBruce/valkyrie#1467]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

**Comment by SylvyaVega** [comment]
Could you please add it to the mission list?

**Comment by vidimus** [comment]
@scrubbless is the one in charge.

@SylvyaVega recomended number of players and expansions used?

**Comment by scrubbless** [comment]
Hi @SylvyaVega 

Unfortunatly I cannot add this with it current path, the repository name has a space which causes issue with the manifest:
![image](https://user-images.githubusercontent.com/32058089/109679250-50ae7c80-7b73-11eb-8d90-47bc8b6b1568.png)


Can you please upload this to a repo that doesn't have any spaces or special characters in the name and i'll add it. Thanks!

**Comment by SylvyaVega** [comment]
@vidimus 3 - 5 players and the expansions: Twilight Sanctuary
@scrubbless Sorry. I think I've corrected it. I'll upload a new issue in case I haven't fixed it yet.

**Comment by vidimus** [comment]
@SylvyaVega you need to update the link on the Opening post. Now it's still linking to the old repository (I've seen you have created a new one instead of renaming the previous one)

**Comment by javierrodriguez94** [comment]
hi @vidimus! let me help @SylvyaVega with that since she is new at github.
AFAIK she updated the folder name in the last commit to remove the space, she changed `Escenario INSANE` to  `EscenarioINSANE`. She already created a new repository but ignore it, I guess it should be fixed in this one: https://github.com/SylvyaVega/INSANE.git
Please check it and let us know if everything is correct
Thanks!!

**Comment by scrubbless** [comment]
Perfect path is clean now. I've added the scenario, it should be online within the hour.
