### ISSUE TITLE
MoM Scenarios not loading (windows v2.5.6)

### ISSUE THREAD

**Issue by supergorgojo** [NPBruce/valkyrie#1502]
Hi

I recently installed Valkyrie (v2.5.6) for windows and figured out that scenarios were not loading for Mansions of Madness.

![image](https://user-images.githubusercontent.com/85885769/121906247-387dfa00-cd2b-11eb-8cc1-9caf53c2f987.png)

Here is the error I´m getting in the log:
![image](https://user-images.githubusercontent.com/85885769/121907917-cc9c9100-cd2c-11eb-995e-2d770171d183.png)

I've tried to run it with admin persmissions, firewall open, older versions and with several language combinations but nothing works.

Thanks in advance for your support

**Comment by scrubbless** [comment]
I am getting the same error, also I had the previous verison and got the same error.


@estarriol @BenRQ  Can you see anything that may be causing this. 
I added a scenario recently, but the path to the ini looks correct and normally I see an error from the grabber.

There are some generic errors from the grabber, but not the specifics I am used to so I can't seem to track down thge cause:
![image](https://user-images.githubusercontent.com/32058089/121920249-c5c34d80-cd2f-11eb-9ba4-857bfe99617c.png)

**Comment by mayjak** [comment]
That's because the new scenario's default language is English in the ini, but it doesn't support English language. https://github.com/Anxelog/bailemascarasbaronesa/blob/main/bailemascarasbaronesa.ini#L5

The scenario list tries to use the user's language and falls back to scenario's default if the user's language is not supported. It won't try to find anything else. Fixing the ini file should fix the problem for now. I'll try to properly fix it with the next release.

**Comment by scrubbless** [comment]
I've removed the scenario for now, once it's fixed I'll readd it.

**Comment by supergorgojo** [comment]
wow, so fast support!

It is working now, I didn´t download any other package, so I understand that your fix was on server side where the scenarios are hosted.

Thank you all :)
