### ISSUE TITLE
[Question] Importing scenario to a new mac

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#1567]
### Description of Problem or Question
Hey there! After a break of about a year i just wanted to start working on my MoM - scenario again. I have a new Mac now, so i was creating a scenariofile on the old one and placed it into the "Editor" folder on my new MacMini. But sadly im not able to see the scenario in the editor of the app. What am i doing wrong? Thank you in advance!

Im adding my scenario and an image of the file directory where i placed it below. I also created a new scenario on this mac ("Scenario1") and im able to see and edit that without problems.

![Screenshot 2022-06-02 at 13 20 29](https://user-images.githubusercontent.com/26793620/171618696-e6cefe9e-382b-4a68-a5de-f0d863f3f2ab.png)

 
[EditorSamantha Soul.zip](https://github.com/NPBruce/valkyrie/files/8823245/EditorSamantha.Soul.zip)

### Valkyrie Version
2.4 now, im not sure about the version where this was created but it shouldnt be much older.

**Comment by vidimus** [comment]
Hello, @Ashgur ,  scenario folder name should be "EditorScenarioX", being "X" a number. Valkyrie won't read it with a different name format. Just try renaming "EditorSamanthaSoul"  folder to "EditorSzenario2".

**Comment by vidimus** [comment]
I've noticed you made the package, so it could be easier to move the valkyrie file of your scenario (EditorSamantha Soul.valkyrie) to the download folder, instead of the editor one. Then, open Valkyrie, go to the editor and select the option "copy". A scenario list will be displayed and your scenario will be showed. Click on it and you can now edit it as usual. Feel free to contact me for any doubt.

**Comment by Ashgur** [comment]
It worked! Thank you very much!!!

**Comment by vidimus** [comment]
You are welcome, @Ashgur 
Do you have any plans for publishing the scenario in English?
