### ISSUE TITLE
[Question] ScenarioDesignerErrorOrProgramBug?

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1653]
### Description of Problem or Question
I'm a new Scenario Designer and am wondering if this is designer error or maybe a bug.  I'm adding a shop to my home brew scenario (for Descent 2E).  I can't seem to display more than four act 1 items.  And they seem to always display the same four items (Mana Weave, Lucky Charm, Ring of Power and Rune Plate), even over several new game attempts.

I've tried different levels of fame and even removed and rebuilt the showshop event but still same result.

The Act 2 items are working as they should, showing random Act 2 items each shop visit.

I own all boxed expansions for Descent Second Edition and have selected them in Valkyrie.

### Valkyrie Version
2.6.0
[output_log.txt](https://github.com/NPBruce/valkyrie/files/14060438/output_log.txt)

**Comment by vidimus** [comment]
@Quantumrunner , maybe you could help with this.

**Comment by Quantumrunner** [comment]
Hey everyone,
this problem is indeed ringing some bells. I think this is a problem that the fame needs to be initiated in the beginning of the mission somehow and then it is necessary to force a restock event. It could also be that the items you define for the shop or initiated incorrectly when adding them through the editor (I think they set a property that should not be set). Please compare your items.ini with my example:

In start event of `Events.ini`  fame is defined: 

[EventStart]
xposition=15
yposition=-2
operations=$%fame,=,2 $%fameimpressive,=,2 $%famecelebrated,=,6 $%fameheroic,=,12 $%famelegendary,=,16 $restock,=,1 PriceXp,=,125 PricePotions,=,50 PotionsInStock,=,2 MaximumDiaries,=,9 RestockWaitTime,=,2 ArdusHealth,=,5
display=false
buttons=1
event1=EventCampaignRules
trigger=EventStart

In `Items.Ini` items are defined like this:

```
[QItem0]
itemname=QItem0
starting=False
traitpool=act1
```

I don't know what the exact issue was but what you could do is check out an example scenario where the shop is working normally (e.g. my scenario [City of the dead](https://github.com/Quantumrunner/ValkyrieCityOfTheDead). Just download the .valkyrie file and unzip it.

I checked again and items are shown normally + restock is also working fine:

Before restock
![grafik](https://github.com/NPBruce/valkyrie/assets/58113888/803061b4-cd50-4d76-a0f8-9f479811aff2)

After restock
![grafik](https://github.com/NPBruce/valkyrie/assets/58113888/da267cbb-8ade-4472-bfbd-8bb774003e3e)

**Comment by afellowspelunker** [comment]
@vidimus Thanks for the quick referral.

@Quantumrunner Thanks for the very informative response to this issue.

I had the $%fame initialized correctly and double checked the QItems were set properly (pool traits set to Act 1 and all traits deselected).  Turns out I just needed to force the restock to make the shop behave properly.

I didn't have a Restock button option setup in the Shop screen by design, but Adding a $restock = 1 to my InitializeQuestFame event did the trick!  A full set of fresh random equipment items are now listed in the shop.  (Note: In this case, the shop is only visited once before the single quest,  I'll have to see if this works for multiple shop visits over a campaign, my next project).

Related note:  This worked on the Act 1 quest I'm working on but while working on a second quest (including both Act 1 and Act 2 items), setting $restock = 1 resulted in less than full item listing in the shop (only displayed 4 items instead of the 8 I requested to be shown).  Setting $restock = 2 seems to have done the trick, displaying all 8 items requested (2 Act 1 and 6 Act 2 items).  (Note:  Again, I'll need to check this behavior for future campaign designs.)

Thanks so much for your work on Valkyrie!  As a late comer to Descent Second Edition, I was bummed when I found out FFG had discontinued it's Quest Vault.  Valkyrie is a wonderful tool!

And a shoutout to MrTantum as well for his Descent scenario editor tutorials on youtube, very nice!

**Comment by Quantumrunner** [comment]
Happy to help! To make this clearer in the future I have created a wiki entry how to handle the shop:
https://github.com/NPBruce/valkyrie/wiki/ShopEvent#close-the-shop

I will close this issue now.

I'm looking forward to see your scenario find its to Valkyrie one day. :)
