### ISSUE TITLE
Enter class data for all expansions

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#361]
Base game can be seen here:
https://github.com/NPBruce/valkyrie/blob/development/content/D2E/base/classes.ini

https://github.com/NPBruce/valkyrie/blob/development/content/D2E/base/items.ini

**Comment by NPBruce** [comment]
The Chains that Rust is done.

**Comment by dchapde** [comment]
PR sent for The Trollfens

**Comment by NPBruce** [comment]
Merged #393, can you please confirm if the gold values are from the cards or RtL?

**Comment by dchapde** [comment]
I used the gold data from the cards, should I have used RtL values?

**Comment by NPBruce** [comment]
Ideally yes, but as long as I know I can update it when I get a chance.

**Comment by NPBruce** [comment]
If you are going to do items in RtL please make a note of what items you see at what fame levels (#285, #286)

**Comment by dchapde** [comment]
Was this data extracted somewhere for me to look at and update tt? what are the variables to use for fame (min, max) ?

**Comment by NPBruce** [comment]
I haven't added any fame values in yet, I am just collecting data in #286 so that I can set values.

**Comment by dchapde** [comment]
I can add more expansion classes and items but it'll be hard for me to verify all of them in-game. Should I put a comment for each items if the cost is from the card or RtL?

For Trollfen I was able to confirm the cost of these items in RtL:
ItemBeltOfAlchemy : 25
ItemBeltOfWaterwalking : 50
ItemDeflectingShield : 50
ItemLifedrainScepter : 100
ItemTrident : 125
ItemDireFlail : 150

Only ItemBeltOfAlchemy was 150 gold cheaper because the item is mostly used to counter Overlord cards.

As for fame, all the above were seen with Fame 16 and lower.

**Comment by NPBruce** [comment]
Thanks.  Just let me know actual fame values seen at if you can.

**Comment by NPBruce** [comment]
And yes either comment in file or here for if the cost is RtL or standard.

**Comment by dchapde** [comment]
Lair of the Wyrm done

**Comment by dchapde** [comment]
Shadow of Nerekhall - done
Mists of Bilehall - done
Manor of Ravens - done

**Comment by NPBruce** [comment]
Thanks!
