### ISSUE TITLE
Event text going outside of the box

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#378]
https://github.com/NPBruce/valkyrie-store/issues/1

**Comment by MrCraigen** [comment]
X

Den 3 maj 2017 15:26 skrev "NPBruce" <notifications@github.com>:

NPBruce/valkyrie-store#1
<https://github.com/NPBruce/valkyrie-store/issues/1>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NPBruce/valkyrie/issues/378>, or mute the thread
