### ISSUE TITLE
Define all MoM monsters as beast/humanoid/spirit

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#42]
All MoM monsters needs to be one of:

beast
humanoid
spirit

This can be done with the "traits=beast" line in the content packs.  This is needed for the correct attack type to be used.  To find out what a monster is it will need to be attacked in the official MoM app and the attack looked up in localization.  It would be great if someone could do this and provide the data.

**Comment by eorahil** [comment]
mmm, comparing with first edition, was removed the "monster" type, instead they created the "spirit". 
We could assume that:
* First edition humanoids still being humanoids
* First edition beasts still being beasts
* First edition monsters,not sure but should be beast.
* Second edition humanlike monsters, supose to be humanoids. The exception is the ghost, spirit for sure.

The problem is that, in order to be sure, we should try every monster in the app.
I suggest to create a post in bgg forum in order to ask for combat phrases and the monster faced.

Concerning suggestions, is there another way of suggest new issues for this project, instead of putting it here. I want to suggest issues but I don't want to create it directly without asking first.

**Comment by NPBruce** [comment]
I think it will need to be checked in the app.  Can be done at the same time as these:

https://github.com/NPBruce/valkyrie/issues/31
https://github.com/NPBruce/valkyrie/issues/44

Feel free to add any suggestions/issues here, if it isn't appropriate I can always close it.

**Comment by NPBruce** [comment]
As for assistance from BGG here is my plan:

1: Implement MoM activations, attacks and a placeholder mythos event.

2: Release 0.6.0 with 'alpha' MoM support

3: Post to BGG/FFG and ask for assistance in getting the data.

**Comment by NPBruce** [comment]
As discussed:

https://boardgamegeek.com/article/25128066
https://community.fantasyflightgames.com/topic/243052-open-app-for-user-content/

**Comment by eorahil** [comment]
Translated to spanish forum: http://www.edgeent.com/tema/125746-app_gratuita_para_escenarios_caseros

I tested some types too. I will put it here as soon as we get all monsters.

- Hunting horror. BEAST
- Witch. HUMANOID
- Dark Druid. HUMANOID
- Dagon Priest. HUMANOID
- Star Spawh. BEAST
- Ghost. SPIRIT
- Shoggoth. BEAST
- Dark Young. BEAST

**Comment by NPBruce** [comment]
Great I will add these for the next release.

**Comment by NPBruce** [comment]
This is important because the monsters aren't usable without this.  I will do some guess work so at least something will happen, data can be confirmed later.
