### ISSUE TITLE
Text loss after save.

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#424]
Last night I was working on my scenario and encountered an issue.  I wasn't doing anything out of the ordinary just adding some tokens, vars, and events.  I saved it (no crash), and then went to Main Menu -> Start Scenario.  Here I noticed that the title of my scenario had been changed to "Scenario 1" or something like that.  I started the scenario and all the text was gone from the events and buttons.  Events and token events are just blank.  All the buttons have gone to "EventName.button1".  I went back to the editor and all the text is not showing.  The events, tiles, tokens, vars are all still there but no text.  I have checked the localization.txt and the only thing there is the very last event that I created.  

I have a backup but would be losing about 5 hours worth of work since that backup.  It's not too bad because all the events, vars and tokens I created in that time are in those files.  It just sucks to have to redo the text.  Most of it can be pulled from the backup.

My theory is that this was caused by the creation of a duplicate event.  I had accidentally done this before and Valkyrie automatically would add the number 0 to the end of the event name, no problems.  In this case though, the events were named the same thing with exception of one letter (Y) being capitalized.
EVENT1        EventPlace_BackyardOuthouse_Sight_Tokens
EVENT2        EventPlace_BackYardOuthouse_Sight_Tokens

When I noticed the duplicate events I deleted EVENT1.  I then saved and the above happened. 
 
I have not tried to duplicate this.  
I am running Valkyrie 1.0.1
I did not have any of the files .ini or localization.txt files open when this happened.
I expect that my missing text data is gone, hopefully there is a way of preventing this from happening again or to someone else.  

[After_Loss.zip](https://github.com/NPBruce/valkyrie/files/997135/After_Loss.zip)
[Before_Loss_5-11-224PM.zip](https://github.com/NPBruce/valkyrie/files/997136/Before_Loss_5-11-224PM.zip)

**Comment by eorahil** [comment]
Opps. This hurts... sorry about this. I will try to find the problem.
Please provide the valkyrie_Data\output_log.txt file so see if something crashed inside.

**Comment by redwolf2** [comment]
I would suggest writing files in a transaction.

1. Write quest.ini.tmp
2. Delete quest.ini
3. Move quest.ini.tmp to quest.ini

When loading the files, look for quest.ini.tmp, if there is no quest.ini

**Comment by cbusbird** [comment]
Here is the output_log.txt
[output_log.txt](https://github.com/NPBruce/valkyrie/files/997266/output_log.txt)

**Comment by eorahil** [comment]
The log doesn't contain useful info but I found something. 
Duplicated event shouldn't be the problem. if there is a case diference "y" instead of "Y" there should be different events. So there should be no problem. But the DELETE action is removing the dictionary. 
In the newest valkyrie versions the file aren't being cleared but last changes are lost. 
Will try to fix.

**Comment by cbusbird** [comment]
@eorahil   I thought it might be related to the "y" "Y" difference because that was the only irregular thing that I could think of that happened right before the text loss.  Are you saying you found an issue that led to the text or loss or just an issue in general?

**Comment by eorahil** [comment]
I found an issue that led all the text loss.
The problem is that I'm on the latest development version that includes the split of the Localization.txt file into many Localization.Language.txt files and there are big differences.
I think the problem is that All texts dictionary empties in some circumstances. In your version, saving the scenario causes to overwrite the Localization.txt file with empty(or default) entries.
BUT in this new format, saving the scenario after dictionary empties doesn't overwrite nothing because it saves a file for each dictionary but as dictionary is empty, there are no languages and no localization files are saved. So the previous localization files remains the same but last changes won't be saved.
The problem is the same but consecuences are less. Anyway it is a but and we must fix it. Texts dictionary shouldn't get empty after deleting.

**Comment by eorahil** [comment]
I'm prety sure that clicking on this empty buttons when deleting causes all texts to be deleted.

**Comment by eorahil** [comment]
I will disable these empty buttons. I think it's enought to fix the problem.

**Comment by cbusbird** [comment]
@eorahil The deletion list was double spaced.  It is entirely possible that I accidentally clicked on the empty space instead of the Event name.

**Comment by cbusbird** [comment]
I will be more careful next time :)

**Comment by eorahil** [comment]
Sorry about your work loss. These things are possible in this developing stages. Thank you very much for giving the clue to find the bug. NPBruce had a similar issue few weeks ago but we couldn't reproduce it.

**Comment by NPBruce** [comment]
That sucks.  I have released 1.0.2 to fix this problem.  Just as an FYI I like to work in a git repo and perform a stage before saving in the editor so I can validate the changes if this workflow helps you.  Hopefully no more of this type of bug slips through though.

**Comment by cbusbird** [comment]
Folks, I'm really impressed with the response time and fix on this issue.  The fact that I submitted the issue this morning and that there is a new version with the fix already is pretty awesome.  I'm much more excited about helping find the issue and getting the fix then I am disappointed about losing the text data.  This is a really cool project and I'm happy to help contribute.

**Comment by NPBruce** [comment]
redwolf2: The problem is how far do you go?  How many backups?  What about diffs between them?  Then you have a version control system which is reinventing the wheel.  Having a single previous save only works if the issue was found before a second save command, and you clutter things a lot.

I didn't know about Path.Combine(), I have been using Path.GetDirectoryName("c:\\") + "/" + "test" + "/" + "halloworld.txt", which also works but your way is nicer.

**Comment by cbusbird** [comment]
@NPBruce I will look into the git repo.  I also seem to remember reading some post of yours suggesting a text editor to use in tandem with Valkyrie.  I haven't been able to find that post again.  Can you elaborate?

**Comment by NPBruce** [comment]
Here is my work flow.  Note that this is probably overkill for most people and if you aren't familiar with the tools it may be counter productive.

Tools:
* Sourcetree (https://www.sourcetreeapp.com/) to manage git repo
* Text editor (VS Code and Sublime are good options) https://code.visualstudio.com/ https://www.sublimetext.com/

Layout:
* Create a repo somewhere in \<user\>\Valkyrie\ for your scanarios.  Mine is https://github.com/NPBruce/valkyrie-questdata which I also use to build the published quests and scenarios, but you can use anything (including just a local repo).

Process:
* Add things in the editor, save
* Review changes in sourcetree, stage and commit
* Edit things manually where easier (like making 10 similar things or using find and replace)
* Review and stage changes in sourcetree
* Reload and Save in editor.  Review changes in sourctree (should be all non functional), stage and commit.

You can see if the editor has done anything strange at each save and validates your manual changes.  You can also roll back to any previous commit.
