### ISSUE TITLE
Request to add property to MoM Door Token that prevents it from coming back

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#482]
Firstly, I want to make clear Valkyrie is an excellent well built application and (except for one issue) does everything I could wish for and I am very impressed with it.

I do have one issue.  I am working on a MoM scenario where there are multiple alternative pathways to the same room.  This means that the investigators can enter the same room through more than one possible doorway.

The issue is when the door tokens are made visible for the room it is possible that the door has already been entered (and so has already been removed).  To avoid putting back a door that has already been removed, I've added a flag to the door which is raised when the door is removed.  Then I check if the flag has been raised before placing the door.

What would be cleaner would be to do this in the code.  It would, also, be generally useful.

Alternatively, please can someone suggest an easy way of preventing a door from coming back for rooms that can be entered through multiple doorways.

**Comment by cbusbird** [comment]
You need to have conditions for the events that place the explore or sight tokens.  With three or four different ways to enter a tile or room it gets pretty complicated but I was eventually able to get everything working as intended in my scenario.

**Comment by LordPyrex** [comment]
cbusbird is right. When a room is discovered have it assign a variable under the Vars section of the event. Something like 'FoundBallroom' and set it to 1 for true. Then in any event that would add an Explore Token that would lead into that room have it do a Vars Test where FoundBallroom  != 1.

Just like coding != means does not equal. From here you shouldn't have any duplicate Explore Tokens that will appear. If you have more questions about using variables check out [https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars](url)

**Comment by NPBruce** [comment]
As others have said (and in the original description) this can be done but is a little tricky.  I don't see a better way to do it thought - Valkyrie doesn't know what you are doing with the tokens and there may be a very good reason to leave a locked door between two explored rooms.

**Comment by redwolf2** [comment]
Maybe it could be done by using [bit fields](https://en.wikipedia.org/wiki/Bit_field) or something similar. But that would be really counterintuitive for non-programmers.

**Comment by NPBruce** [comment]
If you were going down that path I'd implement structs (bit feilds should only be used these days where the performance is really required, or it is an internal system and not an interface).

Given how vars work, this would just be a grouping of (for example) visible.boolroom.  The only advantage here rather than just visibleBoolroom is maybe you can clear all visable in one go?  Still probably not worth it.

I am however considering a method to query what components (Tile/Token) are visible at the moment.

**Comment by redwolf2** [comment]
Nice insight. I agree, not worth it ATM.

**Comment by NicolaZee** [comment]
Having a method of querying which Tiles are visible would be helpful and would help to simplify the issue.

Currently implimenting entering a room through multiple doors is a pain.
I do not believe either of the two MoM scenarios which currently exist gives an example of this.
Nor does the tutiorial.

**Comment by NPBruce** [comment]
They don't, good idea for a mini tutorial.  Volunteers?

**Comment by NicolaZee** [comment]
I would volunteer but as I am working on a scenario where there are 7 rooms which can be entered from multiple directions I think you may find the issues are more of a pain than you may at first think - or at least I found it so for me : )

**Comment by NPBruce** [comment]
Note that there isn't a problem with removing a token that isn't there.  So whenever you place the tile remove all of the connecting tokens (even if they aren't there) and just tell the player to remove any that connect to the tile.  This is how the official scenarios do it.

Of course if you want to be fancy and have text that tells them exactly what to remove it gets a lot more complicated.

**Comment by NicolaZee** [comment]
Removing the door is not the issue.  The issue is that it comes back.

Take a Room which each can be entered through 4 doors.
Investigator enters the door, the Tile is placed and so is the Doors for the Tile - because it is not visible.
The door is removed and then the Event is called to place the 4 doors.
We then must check which doors should be placed and which not.
Which means a flag for each of the 4 doors that can be entered.

I cannot find a way for the information of which door has been removed to be passed on to the event to place the doors - causing the door to come back.

**Comment by LordPyrex** [comment]
I will try to write a sample of this situation/mini tutorial. I was going to try and do something to provide some more information on how variables can be used to trigger events and prevent others from taking place. This falls under the later.

**Comment by NicolaZee** [comment]
Thank you for offering to do a tutorial : )

**Comment by LordPyrex** [comment]
No problem. I was planning one for using  variables anyways. I'll just make
sure to use something similar to this as well.

**Comment by LordPyrex** [comment]
@NPBruce Do we have a way of creating a folder for demo scenarios? Or would it just be a normal pull request to be added to the downloadable scenarios?

**Comment by NPBruce** [comment]
How I am doing it is adding them all to the existing demo scenario.  You can do this by using a subdirectory and having an event that references another quest.ini.  This reference can't be done in the editor it has to be done manually.  Have a look here:

https://github.com/NPBruce/valkyrie-questdata/tree/master/source/MoM/Demo
https://github.com/NPBruce/valkyrie-questdata/blob/master/source/MoM/Demo/events.ini

If the plan is to have tutorial style demos perhaps the first event will ask if you want to check out new features or see a tutorial, then you can have a list of each as different events.

**Comment by LordPyrex** [comment]
Or maybe the first event can be buttons that lead to different portions of the demo with a token at the end that removes everything and then takes you back to the menu to choose another demo. That way all we would have to do is merge the files since the coordinates don't matter for the tile placement.

**Comment by LordPyrex** [comment]
Although, it would complicate things if someone is trying to pick their way through the code to learn it for themselves.

**Comment by NPBruce** [comment]
Definately prefer separate scenarios.  Easier to maintain and users can copy individual demos.  You can still return to the menu using event1=../quest.ini if you like.

**Comment by LordPyrex** [comment]
I don't have push access for that repository. Can I send you the scenario folder?

**Comment by NPBruce** [comment]
Yep, either that or do a pull request.

**Comment by LordPyrex** [comment]
[VariablesAndDoors.zip](https://github.com/NPBruce/valkyrie/files/1040021/VariablesAndDoors.zip)

**Comment by LordPyrex** [comment]
I still haven't figured out the pull request bit.  I'll have to read some documentation on it.

**Comment by NPBruce** [comment]
Not in a position to test at the moment, can you download and try this package:
https://github.com/NPBruce/valkyrie-store/blob/development/MoM/Demo.valkyrie

**Comment by LordPyrex** [comment]
Was able to run it. Worked fine, now I just need to finish writing the accompanying wiki explaining it all. But that should be easier than having to do a blind example that you can't see in action. Thanks!

**Comment by LordPyrex** [comment]
I might need to add one more event at the start explaining it since I had
originally put that into the scenario quest data screen

**Comment by NicolaZee** [comment]
Thank you for adding the door example.  It helps to have something concrete to look at.

I don't know if this is the correct place to raise this but the example does not seem to me to be correct. 
If you click on the door to the Interior Door all the doors are removed. This gets rid of all the annoying doors to all the other tiles - hooray!

But surely the Doors to the rooms that have not been explored should remain and not be removed?

To do this each door which can lead to a possibly uncovered room must be checked for the Uncovered Tile flag.
If the door is to a Tile which is not uncovered it should not be removed.
This leads to a flag for every tile that may or may be uncovered and an event for every door which may or may not lead to such a tile (as that's the only way to check the flag)

Alternatively - and this is quite possible or even likely -  I may just be even more confused than I first thought!  : )

**Comment by LordPyrex** [comment]
Actually I had an intro for the scenario that explained that it was showing only the doors going into the room. In order to show it going out of the room you would have to create alternate Explore tokens that lay in the same location as the doors leading in.

Those events would each have to have a variable that tests to see if that part of the hallway exists. It would be the same process as the doors that lead in, I just didn't want to over complicate the example so that if someone was looking into the code to see how it was done.

I would be glad to send you a copy of how that whole hallway scenario would be written so that you can see how even the sight tokens would be removed depending on how you traverse the corridor.

**Comment by NicolaZee** [comment]
OK that makes sense and I agree the first scenario now makes sense and should remain as is.
But I think it would be worth adding to the tutorials the complete solution - one which includes the doors going out.
Otherwise it's only half the picture.

**Comment by LordPyrex** [comment]
I think you've got it! Having the tokens set like that will only spawn the
ones that you need and will remove the ones you don't once they become
obsolete. I will make an advanced version which plays with all the tokens
on the field including the sight tokens

**Comment by NicolaZee** [comment]
Hooray!  It makes a lot more sense and I now get why 2 doors are needed.
A big thank you for your help!

I think you will agree it is a bit complicated.

It would be nice to have - as Bruce put it -  'a method to query what components (Tile/Token) are visible at the moment.' It would make it a bit cleaner.

On the other hand I get that it's not essential and there are more pressing urgent issues.

Like not having to select investigators when trying out a tutorial : )

**Comment by LordPyrex** [comment]
@NPBruce I have a scenario that won't open when I try to start it. I can edit it, but it doesn't show up on the selectable scenarios to play. Any ideas? 
[BrokenScenario.zip](https://github.com/NPBruce/valkyrie/files/1043062/BrokenScenario.zip)

**Comment by redwolf2** [comment]
@LordPyrex Better open up a separate issue for it.

**Comment by LordPyrex** [comment]
It was in reference to this ongoing thread, but I can split it.

**Comment by redwolf2** [comment]
My guess would be, that it is because of the unnessessary sub folder inside the archive with the same name as the archive.

**Comment by LordPyrex** [comment]
No, that was just from zipping it up before sending it, sorry

**Comment by redwolf2** [comment]
Sry, saw it myself, thats not it. Can reproduce the problem here with your scenario.

`(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.Content.DictionaryI18n.AddRaw (Assets.Scripts.Content.DictionaryI18n dictToCombine) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Content.DictionaryI18n.ReadFromFileList (System.String basePath, IEnumerable`1 localizationFiles, System.String newDefaultLanguage, System.String newCurrentLanguage) [0x00000] in <filename unknown>:0 
  at QuestData+Quest..ctor (System.String pathIn) [0x00000] in <filename unknown>:0 
  at QuestLoader.GetQuests (Boolean getHidden) [0x00000] in <filename unknown>:0 
  at Game.SelectQuest () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.MainMenuScreen.Start () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.MainMenuScreen.<MainMenuScreen>m__0 () [0x00000] in <filename unknown>:0 
  at UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <filename unknown>:0 
  at UnityEngine.UI.Button.Press () [0x00000] in <filename unknown>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <filename unknown>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <filename unknown>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename:  Line: -1)`

**Comment by NPBruce** [comment]
The quest is set to hidden, which does exactly that!  This is so you can have sub quests which can't be started by users.

**Comment by redwolf2** [comment]
Ignore the log I posted. Bruce won the race. 

Set this:
```
; Saved by version: 1.2.0
[Quest]
...
hidden=True
```

**Comment by LordPyrex** [comment]
OMG, I'm an ID10T

**Comment by NicolaZee** [comment]
I think you are a hero for taking on making a tutorial for what is the most complex issue (I've so far come across) in implementing a MoM scenario. Everything else was fairly self-explanatory.  

So a big thank you for your time and patience.  I am certain it will help others.  There are several 1st ed scenarios (especially fan written ones) where rooms can be entered from multiple directions so anyone converting these will come across this issue.

**Comment by LordPyrex** [comment]
@NPBruce Here is an advanced version of that multi room scenario. In case someone wants a more through idea of making something like this.
[AdvancedTokensAndVariables.zip](https://github.com/NPBruce/valkyrie/files/1045570/AdvancedTokensAndVariables.zip)

**Comment by LordPyrex** [comment]
@NicolaZee Thank you for that, but I really just consider it sharing what I have learned through trial and error. NPBruce and the other coders have created a solid platform to stand on as far as putting it all together.

**Comment by NicolaZee** [comment]
Thanks your example.  It definitely helps.  I've tried it and it works.  I am much less confused - so a big thanks is in order.

In regards to examples I think they should be kept as separate zip files - so people can choose which example to try out.  Otherwise once there are hundreds of such examples it will be confusing and wasteful.

I've been breaking it down into its steps and I'm 100% OK with the removing the doors going in.

I've still got an issue with adding the doors going out.  The check for the doors going out is a set of events with each event matching a door checking if the room has been 'entered'.
All events for placing the doors out will be triggered from the Place Tile Event

[EventPlaceTile]
buttons=1
event1=EventPlaceDoorOut1 EventPlaceDoorOut2
add=Tile0

But Instead of firing off all both events, only the first event that matches the condition is triggered.  Consequently each door placement event must (in turn) call the subsequent door placement events in a chain.
EventPlaceDoorOut1 calls EventPlaceDoorOut2
EventPlaceDoorOut2 calls EventPlaceDoorOut1

This is feasible with 2 doors going out but what about 3 doors going out?
EventPlaceDoorOut1 calls EventPlaceDoorOut2 calls EventPlaceDoorOut3

What happens if Door1 resolves but Door2 does not and Door3 should be placed?

What would be great for 'Next Events' would be (as well as 'Random' and 'Ordered'), an additional type 'Concurrent' which would fire off all the events.
But I do get that this would be a significant amount of work and it's not likely to happen. : )

**Comment by NPBruce** [comment]
> What would be great for 'Next Events' would be (as well as 'Random' and 'Ordered'), an additional type 'Concurrent' which would fire off all the events.

The reason I don't do this is what if event1 changes the conditions for event2?  What is the expected behaviour?  You also need to understand the stack because if event1 calls event3 that will happen before event2, and will have implications on what is enabled.

**Comment by NicolaZee** [comment]
I am not suggesting that 'Concurrent' should be the default - definitely not - just an option.  If anybody decides to use it they should have enough understanding not to mess things up.

But this (to an extent) is true even with the existing sequential set of events. If Event1 calls Event2 than then calls Event1, the system (perfectly reasonably) goes around in circles.

What you seem be arguing (and apologies if I have the wrong impression) is that because somebody might get things wrong you don't want to add what seems to me potentially useful functionality.  In very rare circumstances it may even be necessary - although to be frank I'm not certain if this is the case.

**Comment by LordPyrex** [comment]
There actually is an example of nesting in my advanced example. If you look at the door placement that would lead to Halls two and three, you can see that I've called the function for place creating the door on the left through 2 different chains.

The first is a continued chain of events. When EventCheckHall2FromIH runs and passes it places the door leading to the Hall north, the next event in the chain is EventCheckHall3FromIH which goes on to place the door to the west.

The second is setup to run EventCheckHall3FromIH if EventCheckHall2FromIH fails. This is done by having the event listed in order of next events. That way if the north door doesn't need to exist, then it will loop back around to check to see if the third door should exist.

Concurrent would actually complicate the way the system evaluates things. You'd have multiple text boxes launch and once started there wouldn't be a way to control which path you are trying to follow at any given time.

If you look at the way even the FFG scenarios work, it's very linear. Do this, then that, until it's all been done in order. Sometimes it just takes more logic statements than you thought to make it all work.

**Comment by NicolaZee** [comment]
Thanks - at least I'm starting to get into my head how the multiple doors placement works sequentially.

I'm coming to the conclusion that a big scenario with lots of multiple access doors may be beyond my  abilities.  : )

Although I agree concurrent is more complex for the system, I don't believe it's more complex for the designer.  When placing the doors out, I don't see why I need to worry about the order the doors are placed. 

You are right FFG scenarios are very linear in terms of placement of tokens but sometimes I find that annoying.  I was hoping to get away from the repetitive clicking of the 'Continue' button : )

Oh well at least I understand the issues better.

**Comment by NPBruce** [comment]
I have a solution for you, but first some more information:

The main reason I don't have this feature (it would actually be easy to add) is that when you have an event only starting one other event it is obvious when the test conditions are checked.  When you have branching trees and multiple paths there are many different ways this could occur and greatly increases confusion.  Having said that if the solution I am about to give you gets used much (I hope not) I will add in the option you suggest.

From the event documentation:

"A trigger can also be "Var<name>" where name is the name of a var that starts with '@' (with the '@' removed). In this case the event will trigger at the end of an event that sets the associated var to 1. The var will be reset to 0 before this even occurs. After this event and it's following events have been resolved any events following the calling event will be resolved. Note that if vars have changed the possible outcomes from the calling event will NOT be redone, so this method of calling events is not recommended in most circumstances."

What this means is you can do this:

Event1 sets @trigger = 1.

Event2 and Event3 have triggers of Vartrigger.

WARNING:

1: Event2 and Event3 should not have conditions that are changed by each other, for the reasons mentioned above.

2: The order of execution is *UNDEFINED*.  What this means is that sometimes Event3 will happen first.  In reality because of how things work 99% of the time the event that is first in the editor will be first in the game, however this is not guaranteed.  If the memory manager needs to move things around it MAY go the other way.

**Comment by NPBruce** [comment]
To provide some context the system described above is designed to be used for D2E travel events.

So I  am travelling from A to B and I want a travel event inserted in the middle, as a generic event, and I need to continue with the B event even though the travel event itself doesn't know where I am.  So it looks like this:

Event A
Sets @travel
Button Travel to B Triggers EventB
Button Travel to C Triggers EventC

Event B
Sets @travel
Button Travel to A Triggers EventA
Button Travel to C Triggers EventC

Event C
Sets @travel
Button Travel to B Triggers EventB
Button Travel to C Triggers EventC


EventTravel
Trigger vartravel

This will inject EventTravel into the event stack from different places, and EventTravel doesn't need to know where to go back to, which is more important when there are a lot of places you can go to/from.

**Comment by NicolaZee** [comment]
Hooray!
Now that sounds more like it.
A big thanks.

I'm also going to add blocked door tokens to save my sanity.
I have got one room with 4 doors out - which I now realise is not a good idea,

**Comment by NicolaZee** [comment]
Just one final request for clarification.

With LordPyrex's well thought out (and very helpful) example, I believe it is in effect a 2 door out example - because we don't need to check if the starting tile is visible.

How does it work for a 3 door out - where a check of 'uncovered' is needed for each of the 3 doors?

**Comment by NicolaZee** [comment]
I've just tried a quick test for placing doors using the var triggers and it worked great.
So, a big thanks.
It has the following advantages:

1) It scales
It does not matter how many doors there are - the method works the same.

2) The logic is cleaner
There's no need for a chain of doors out placing events calling each other.

3) It reduces 'continues'
I found with the previous approach I was doing all the doors out at the end and finding I needed a continue.  This could just be because I was getting confused :)

I will agree there is a danger that the doors may pop up in an odd order but that to my mind is a small price to pay.

So, I'm happy.
