### ISSUE TITLE
Request for clarification of what the MoM Token's Tests Variables are used for.

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#495]
I think I understand how tests for Variables for Events work.
I am baffled at what the tests for Variables for MoM Tokens are used for.
The option to set them is on the UI Page for MoM Tokens.

I was hoping that if the test condition for the variable failed then the Token would not be made visible.  This would be useful for not placing a Door that is not needed.
But it does not seem to do that.  

So please can some kind soul explain what is it used for with MoM tokens?
I suspect I'm being dumb but I'm totally baffled.

**Comment by cbusbird** [comment]
I believe that the assign var section of a token will allow you to assign a var when that token is executed (like Search or Explore it).  I'm not sure what the test var section is for.

**Comment by LordPyrex** [comment]
Tokens are nothing more than paused events. One event places a token, then interacting with the token starts the action again.

For the Token not to be made visible, just place your test on the event that would place that particular token. You wouldn't want the test to be placed on the token itself because by that point it already exists. The tests on the token would affect the potential results of the next event that the token would have.

**Comment by NPBruce** [comment]
This is a valid point, it is there because tokens work like a subclass of events, and thus have conditions because events have conditions.  Using them will only stop anything from happening when you click the token, which isn't very useful.

2 Options:

1: Remove the conditions section from Tokens to avoid confusion.

2: Make the conditions prevend the Token from being added.  This has two problems:
 - What happens when the conditions change?  What if the event that adds the token changes whether the tokens conditions are met?
 - What if there are existing scenarios that use this for some reason and the functionality changes?

Given that I can't see a lot of use for 2 I am planning to do 1.  Anyone add comments if you disagree.
