### ISSUE TITLE
Horror values on monster icons

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#498]
I'm not sure how feasible or possible this would be but this is a feature that I have wished for in the FFG app as well.

If you are like me (I know I'm not the only one) and have painted and based your MoM minis on acrylic and discarded the fugly black bases the Horror numbers on a monster are pain to lookup.  I think it would be really cool to impose the Horror value of the monster in the bottom right corner of the monster icon.  At least during the Horror check phase, I think this would be convenient for all players and would a big benefit for players like me.

**Comment by NPBruce** [comment]
Also evade while I'm at it.

**Comment by LordPyrex** [comment]
Can these also be made editable for custom monsters?

**Comment by NPBruce** [comment]
While this would be possible it creates a problem, because most people are going to read the value on the token, and it will be confusing if the screen doesn't match.  I guess you can just have a message when the monster spawns explaining that it is a special moster and don't use the number on the token.

I am not sure how useful this is anyway.  You might want to force the special horror by having a crazy high number, but you could just put this effect into the activation instead.  Evade is probably more useful, perhaps you could just say in this case that there is a special rule where this monster must always be evaded, regardless of other monsters in the space?

**Comment by LordPyrex** [comment]
That's what I have done so far, just thought that if it was visible elsewhere it might act as a reminder, not a big issue though

**Comment by Hobbeslionheart** [comment]
If we're going the completionist route, then strength should be included too for breaking down doors.

I'm wondering if these numbers would pop up during their respective phases (Evade for Investigator Phase, Strength for Mythos, and Horror for Horror phase), but that might mean a significant alteration to each portrait of the monster.

Another option is when you click on a monster, you can just show a scan of the tokens. For Descent, a scan of the cards would honestly be very helpful especially if people want to play with monsters they don't have.
