### ISSUE TITLE
Descent QItems

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#499]
Is there a possibility to remove a QItem which was granted by an event?

I have an event which awards the heroes an item by "add=QItemExample", because they need to know the stats of the item. 

Depending on the outcome of the event the heroes may either keep the item, or they should lose it. Unfortunately "remove=QItemExample" does nothing here, and the item is still in the inventory.

By the way, is there an ETA for the implementation of the Descent items?

**Comment by NPBruce** [comment]
I can have remove remove the item from inventory if the party has it.  All D2E items should be done, are there things missing?

**Comment by DelphiDie** [comment]
Strange, I seem to be only getting iron shields and leather armor

**Comment by NPBruce** [comment]
In the demo shop you only get those if you don't increase fame in the first quest (don't have a fame button in the shop).  This is because at minimum fame and the filters I have on the two shop slots mean that is all that fits.  I have the fame levels set so that each time you gain fame you go up one bracket and will get different items.

**Comment by DelphiDie** [comment]
Thanks for the explanation Bruce, that explains it. I set the first threshold $%fameimpressive,=,10 to 10 and the first quest only yields 2 to 5 fame. Is there a list of the items, fame levels, traits and prices somewhere?

**Comment by NPBruce** [comment]
Have a look at the items.ini files for each of the expansions in content/d2e
