### ISSUE TITLE
Able to pick investigators from content I don't own

### ISSUE THREAD

**Issue by rafbel** [NPBruce/valkyrie#508]
Hello,

I would like to start off saying that what you have created for the MoM 2nd Edition community is amazing. This offers so much more to the game in terms of  content and replayability. Thank you so much.

Now let's get to the issue:

I chose the scenario "Exotic Material", and when I went to the screen that allows our group to pick our investigators, all investigators were available to us even though I only own the base game and no expansions. I checked to see if all the extra content was unselected and indeed they were. 

I know this changes little in terms of playing the game since we are perfectly able to choose only the investigators I own, but it would be cool if it was able to only show the investigators that were truly available.

Once again, thank you so much for making this happen!

**Comment by NPBruce** [comment]
This is tricky because others want to play with them as they have the cards available in the box.  Maybe this needs to be broken up more with additional controls.  Other opinions?

**Comment by rafbel** [comment]
What I would suggest is checking with some simple conditionals what contents the user owns just after selecting the scenario and store that information for anything you'd need throughout the scenario. That way Valkyrie would know what investigators are available to the users and any other info that you'd need like cards and tiles. Don't know how complicated that would be, but the user is already able to select content on the Main Menu, so maybe it would be cool to see it implemented.

Also, I am fluent in both Portuguese and Spanish, so if you need any help translating stuff manually or are in need of a spellchecker, feel free to give me a shout.

**Comment by redwolf2** [comment]
Maybe add the Conversion Kit as a separate Content.

**Comment by LordPyrex** [comment]
It would give access to those monsters and character tokens as well. I've
heard how some people only use the monster tokens in place of the figures.

**Comment by Dungdae** [comment]
Another option would be, close to redwolf2 suggestion, add an **Conversion Kit: Investigators** in the contents menu, which only unlocks the investigators.

**Comment by redwolf2** [comment]
The problem is how detailed the select content section should be and if it is worth it. Of course, there are always power users that want to configure and tweak every fine detail. One could break down all content packs as investigators, items, monsters, tiles and so on, but is it worth it? If someone is not using the investigators just don't select them is rather easy.

Here are other possible requests:
* Only include the Conversion Kit investigators, but not the monster
* Only include the Conversion Kit monsters, as the player is playing with tiles only
* Only include the Conversion Kit items.
* Have all the investigators, but not the butler

These are just examples how problematic it could get, going from simple to detailed and should not devalue all your other suggestions.

Another idea is to just have some quick toggle on/off buttons in the chooser to show/hide investigators by content pack. The app could save the last state of those toggles.

**Comment by Dungdae** [comment]
In fact, another option would be to change the entire layout of the contents selection menu. Point it towards a more Drop down menu fashion, with e.g. following categories: **Expansions**, **1e. contents** and **Conversion kit**

When selecting one of the categories, a drop down slider shows up, which enables to select contents from tick boxes (all bullet points).
Something like this.
**Expansions**
- Beyond the threshold
- Suppressed Memories
- Recurring nightmares

**1e. contents**
- Forbidden Alchemy
- Call of the wild
- Mansions of madness first edition

**Conversion kit**
 - Investigators
 - Monsters
 - Tolkens

This way customisation is possible, while still simplifying the overall layout.

**Comment by rafbel** [comment]
You guys convinced me that maybe the simplest solution might be the best. Maybe on the content page have a simple checklist allowing the user to enable/disable investigators, tiles, and/or monsters from that expansion/1st edition content kind of like what @LordPyrex suggested. 

That would probably make it more customizable and simpler to use.

**Comment by NPBruce** [comment]
My current Ideal is this:

`/--------------------\
|                      |  Inv. |
|  Pack            | Mon.|
|                     | Tile |
\--------------------/`

Selecting pack will toggle all, or you can toggle the parts.  Thoughts?

**Comment by NPBruce** [comment]
Also, how is this handled by scenarios?  Can you have a scenario that requires the monsters from the conversion kit but doesn't need tiles?

**Comment by Dungdae** [comment]
In my opinion, yes the conversion kit can definitely be included without the monster mini's. People themselves can decide if they can accept to use a cultist mini for replacing a witch. The in game mechanics of diversity in monster encounters is simply too valuable!

The important part is to ensure that a scenario does not require map tiles from the expansions.

So in short: when editing a scenario there could be a small box "Include material from conversion kit", that is grayed out (and automatically selected) if any violating map tiles are added/already in the scenario.

**Comment by NPBruce** [comment]
> that is grayed out (and automatically selected) if any violating map tiles are added/already in the scenario.

Can't do this because they might be only placed if you have them, there is no good way for automatically determine what components in a scenario are just there as an option if available and what components are required.

**Comment by NPBruce** [comment]
OK so the plan is this:

Content will have sub pages like Descent.  The first page will be boxed expansion, currently only having BtT.

The next will be Figure and Tile Collections, with SM and RN as single options each.

Then there will be a 'Conversion Kit' page.  Under there it will have listings for each of monsters, investigators and tiles for each of 1E, FA and CotW.

This will require a quest format update as there will now be 9 codes replacing the 3 currently in use for required expansions (you will need to say which parts you need).

The currently selection configuration will be upgraded when you run a 1.3 build.

Lastly the first pass of this for 1.3 prerelease won't support translations because I need to do #344 to support other languages here.
