### ISSUE TITLE
Help needed editting campaigns 

### ISSUE THREAD

**Issue by DakonBlackblade** [NPBruce/valkyrie#513]
So Ive gotten quite good at editting quests now, made a few of my own, all work pretty well and things happen like I mean them to. However Im still lsot at how to string everything together in a campaign, I got some things, like how to add gold, Xp, fame by reverse engineering the 1.1 demo feature but its hard to understand that demo cause when you put it in the quest editor it becomes a bunch of different parts. Bottom line is I don't realy know how to get the campaign going, how can I set the campaign map and have all the quests ancored to it

I know this is a lot to ask but is there a step by step guide about how to start the campaign editting anywhere, or can someone try to explain it to me. I feel like that if I get the basics of it I can probably make better sense of the 1.1 demo and go from there.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/wiki/Campaign-Support

**Comment by DakonBlackblade** [comment]
I still don't quite get how I make the initial set up of the thing. I understand a bunch of stuff in the middle of it (I think), but the initial setup is confusing me still. Is it an UI element with a var, an event with tokens that call for other events or what ?

**Comment by NPBruce** [comment]
That link is outdated, I have removed the page.

There is nothing special about 'campaigns', there are a whole lot of different features you can use to implement them.  Quests can start other quests to string things together, which is why you see them as different entries in the editor.  You can break it up as much as you like, or have everything in one massive quest, but that probably isn't manageable.

Most of what you are asking is about UI components, which has a tutorial here:
https://github.com/NPBruce/valkyrie/wiki/TutorialUIElements

Note that any UI component is also a button and works just like a token.

**Comment by LordPyrex** [comment]
@NPBruce I'm cobbling together a quick demo for this example. Does the current interface still require a manual edit to add quest chains?

**Comment by NPBruce** [comment]
Yes, that is still manual.

**Comment by LordPyrex** [comment]
Okay, just wanted to make sure. I'm not sure what else I can add into this to make that part easier to understand.
[UIMapExample.zip](https://github.com/NPBruce/valkyrie/files/1059515/UIMapExample.zip)

**Comment by DakonBlackblade** [comment]
That was realy helpfull ty.
