### ISSUE TITLE
Increase Maximum Investigator Count

### ISSUE THREAD

**Issue by Hazzerd88** [NPBruce/valkyrie#518]
Hello,
     I'm the moderator of the subreddit for Mansions of Madness. I have a player asking for the ability to add a sixth and seventh player to there games. I don't know how much this will add to your project but I thought it was an interesting idea. Please come joins us at https://www.reddit.com/r/MansionsOfMadness2E/ and partake in the discussions.

**Comment by NPBruce** [comment]
I already have the ability to change the maximum, but it is limited to 5 entirely because the existing UI doesn't have space for more portraits.  Clearly this isn't a huge issue and a UI redesign could remove this limit completely.

PS: Anyone have good UI ideas for investigator selection?

**Comment by Hobbeslionheart** [comment]
I would say the main reason they don't accept more than five players is because the scenario is optimized for a max of five players. Designing a scenario that can accommodate 2-5 players is hard enough, but then balancing it for a sixth and seventh especially with a potential four actions each round would be more difficult. We do have the ability to restrict the number of investigators and that could just be the work around for scenario designers.

That said for UI adjustment, you could just shrink window of investigators selection and add the portraits on the right. You could have up to ten investigators.that way.

So needless to say, I'm not sure I would add this feature just yet.

**Comment by redwolf2** [comment]
IMO this would be a override value in the options to increase or lower the default min and max values and it is at the users risk, that the scenarios might get unbalanced.

**Comment by cbusbird** [comment]
I've got mixed feelings on this one.  I think that 7 investigators breaks the the game a bit.  I have a hard time imagining a map/scenario that works for 2 and 7 investigators.  At the same time I agree with redwolf in that much about Valkyrie breaks the rules so if it can be done "why not".

The way I would like to see it implemented is on a "per scenario" basis.  Like scenario A you are unable to pick more than 5.  But scenario B let's you choose 4 - 7 investigators.

I guess I wouldn't want players playing a scenario that I created for 2 - 5 with 7 investigators.  But the idea of a huge map for 7 players is interesting.  Geez that would be a long game.

**Comment by NPBruce** [comment]
That is what I meant, right now a scenario can limit the maximum investigators to less than 5, but can't increase it beyond 5.  Only reason this limitation is in place is the selection UI screen.

**Comment by redwolf2** [comment]
The most simple way would be to remove the left selection and only use the list. Or keep the list, and stack the investigators on top of each other (like playing cards), if they get too big. Instead of a stack, the left selection could be scrollable.

**Comment by NPBruce** [comment]
Max now 10.
