### ISSUE TITLE
Sharing scenario

### ISSUE THREAD

**Issue by prilogon** [NPBruce/valkyrie#538]
[kadakian.zip](https://github.com/NPBruce/valkyrie/files/1094883/kadakian.zip)

I have this scenario and I like to share. What I have to do?

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

**Comment by Hobbeslionheart** [comment]
Since we're getting a lot of these questions/requests, may I suggest maybe adding a publish button on the Scenario Editor either in the main menu or in editor tools. The publish button at its simplest would display a text box with the contents of the Wiki page for publishing. If even possible or desired, it could do the step by step instructions the wiki says within the editor.

The latter may not be possible or would take a considerable amount of work, but at least the publish button for now will be more obvious and noticeable and can provide the said guidance without having to look outside the editor.

As Bruce has seemed to permit, my suggestion would be once uploaded to make a "page" for your quest/scenario that people can comment, make edits and/or suggestions to on by creating a new issue and closing it so that Bruce doesn't have to track it, but if one looks through closed issues, it can still be active for commenting.

**Comment by redwolf2** [comment]
@Hobbeslionheart While you suggestion could provide some mid-term solution, the long term goal is to provide a separate page with a forum and store for quests and scenarios. See https://github.com/NPBruce/valkyrie/issues/111

**Comment by NPBruce** [comment]
My current mid term solution is a little different.  I want to add a 'package' option to the editor which will generate a .valkyrie file and a manifest file.  You can then host these anywhere you like with direct http access.

Then just send me the link to where ever you put them and I will add that to a master listing.  Once you are added authors have direct control over their content and can make edits without me having to be involved.

**Comment by redwolf2** [comment]
@prilogon Everything ok? You didn't reply for a while. Any problem I could help you with? If you have trouble with GIT, I could check it in for you.

**Comment by prilogon** [comment]
Hi @Hobbeslionheart, I dont know how to do the steps 3 and 4... Could you create a pull request for me?

**Comment by redwolf2** [comment]
No problem, but give me 10 hours.

**Comment by prilogon** [comment]
Thanks @redwolf2 ... I used the wrong nick before, sorry

**Comment by redwolf2** [comment]
Added pull request. https://github.com/NPBruce/valkyrie-questdata/pull/23
It should be available, when this pull request is closed.

**Comment by NPBruce** [comment]
Updated.  Note that this was created in 1.3.0a which is a prerelease which uses a different download source, you will have to use a stable release (1.2.2/1.3.0) to see the download.

**Comment by redwolf2** [comment]
Im working on the normalization and will translate it later

**Comment by prilogon** [comment]
Thanks! I've seem on 1.2

**Comment by redwolf2** [comment]
You can download 1.3.0 here: https://github.com/NPBruce/valkyrie/releases

**Comment by NPBruce** [comment]
I would rather use this link:

https://github.com/NPBruce/valkyrie/releases/latest

It will always point to the latest stable release, the link above includes prereleases.

**Comment by prilogon** [comment]
Great! I will test later, but I loved to know that is possible to test in the editor

**Comment by redwolf2** [comment]
I added a pull request for the german translation https://github.com/NPBruce/valkyrie-questdata/pull/26

**Comment by NPBruce** [comment]
@prilogon if you give your OK I will merge these changes.

**Comment by prilogon** [comment]
OK

**Comment by NPBruce** [comment]
Done.

**Comment by redwolf2** [comment]
I added a rough english translation https://github.com/NPBruce/valkyrie-questdata/pull/28

**Comment by NPBruce** [comment]
@prilogon if you give your OK I will merge these changes.

**Comment by prilogon** [comment]
OK
