### ISSUE TITLE
Messages Log Window

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#54]
Like original App and for debugging purposes a message logger window inside game could be good, even needed, in order to track correct behaviour.
With an extra "DEBUGGER MODE" for expanding logger window's messages with more info for developers.

**Comment by NPBruce** [comment]
Yep it's on my list, should be here too.  Note that there is a log created in the data dir which does have some quest state info (like setting and clearing flags).

**Comment by NPBruce** [comment]
Debug split into #83

**Comment by NPBruce** [comment]
I have added the log window, however Masking (not showing text outside the window) only work if I use the newer "UI/Default Font" Shader.  The probably with this is that it is buggy and often showed text only in black.  My work around for this bug was to force the use of "GUI/Text Shader" which is standard on the materials imported with the font.

The problem is "GUI/Text Shader" does not honour the mask, and text goes everywhere.

This looks like it will be painful to fix.

**Comment by NPBruce** [comment]
Split text overflow to #84
