### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#558]
We've done a new scenario but in spanish. I have a *.doc document with all the text of the mission with all the tokens and phases, also mythos. If someone could help with the translation I can rewrite the location file to upload it. I've tried to translate 4 pages, but ii'm not sure if they're ok. I can finish and upload it with some kind of clunky english, or wait for some help and work on a more accurate version.
[SUEÑOS RECURRENTES_Vrev2-Bad-English.docx](https://github.com/NPBruce/valkyrie/files/1112753/SUENOS.RECURRENTES_Vrev2-Bad-English.docx)

**Comment by redwolf2** [comment]
I may check it out tomorrow.

**Comment by eorahil** [comment]
I suggest to use the Localization.X.txt file instead of docx files.
How did you create this doc file, by copying the texts inside Valkyrie.
I think the better way is to copy the Localization.Spanish.txt file into Localization.English.txt and using a text exitor like Notepad++ to translate the texts. You just need to add double quotes if your translation uses commas and the original one didn't but I think it's a faster way than pasting into a docx file. After all you will need to go back from docx to localization file again. Or you will use valkyrie to paste every texts?

**Comment by EtiCarasoft** [comment]
[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/1115760/Localization.English.txt)
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1115762/Localization.French.txt)
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/1115761/Localization.Spanish.txt)
These are the files from the adventure. 
I used the Doc file to think the adventure and what i wanted to explain inside.

**Comment by redwolf2** [comment]
I will have a look at it now.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/533

**Comment by toyboi** [comment]
will there be polish language  sooner or later ?

**Comment by NPBruce** [comment]
Any time someone submits a translation.

**Comment by EtiCarasoft** [comment]
An user has found a bug in the adventure I've solved it, what files do I have to reupload as a pull request?

**Comment by NPBruce** [comment]
You can replace them all it will only track the files that change.

**Comment by EtiCarasoft** [comment]
ok i'm changing some quest.ini info with redwolf2 advises.
