### ISSUE TITLE
Request for a zip file for latest Windows version of Valkyrie 1.4.2 

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#574]
Please can the download for the latest Windows version of Valkyrie 1.4.2 include a zip file as well as an exe?
There is only an exe and my virus scanner does not like unknown executables from unknown sources to be run.
It used to be a zip file and it worked fine before.

Thanks

**Comment by redwolf2** [comment]
What virus scanner do you use? Remember: Virus scanners are snail oil, that give yourself a false idea of security. This issue is the best example for it. A so called false posivite. It may also be the cause of more security problems as a virus scanner is parsing and crawling files a process that is prone to attacks. At the end of the day the hole in your security could be your virus scanner. There are nice more ramblings of an ex mozilla [employee](http://robert.ocallahan.org/2017/01/disable-your-antivirus-software-except.html).

Maybe bruce could provide the setup as a msi file,

**Comment by NPBruce** [comment]
I have added a zip and will do so for future versions.  It is worth noting that if Valkyrie contained malware this wouldn't help at all, you still have to run Valkyrie, it just bypasses the warning.

**Comment by NicolaZee** [comment]
Thank you for adding the zip file.
That is very kind and I think you'll find others will appreciate this.

I do have my virus scanner set to high settings (and I can get around it) but its just a hassle which does not seem to gain me much.

I agree with redwolf2 that virus checkers give a false sense of security but half a loaf is better than none!
And some virus checkers are almost as bad as having a virus.  I hear McAfee has upped its game but it used to cripple pc's - and many large companies used it regardless of this.  I use Norton's which I am mostly happy with - although the annual subscription is a bit expensive compared to the others.

**Comment by redwolf2** [comment]
If you really need one, go for Microsoft Windows Defender as this is the least system invasive scanner.

**Comment by NicolaZee** [comment]
Although we will have to agree to disagree on Anti-virus Software, I will agree that false positives are frequent and annoying.

I've just got a warning from Norton's on Outlook!
It seems Microsoft has rolled out 8229.2103 of Office without warning Nortons.
