### ISSUE TITLE
Trigger Event: Defeated Spawn of a Random Group

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#579]
So my objective is to have an event that would trigger upon a group of monster's defeat and change a variable that would give them priority of spawning reinforcements the next turn. My groups are random, and to the best of my knowledge, all triggers are based on a certain monster type or a custom monster. The easy fix would be to make them not random or to create a custom monster, but this then limits the monster in play and reduces replayability.

**Comment by LordPyrex** [comment]
I don't have a lot of experience on the Descent side of Valkyrie yet(still practicing with it), but couldn't you use a 'Defeated Monster' monster trigger in order to do this for all monster types? 

As each monster in the group is defeated the defeated trigger can increment a counter. When a particular counter reaches a preset number at the start of a round then it can spawn reinforcements of that particular enemy type. While this would be tricky to set up in the first scenario, you could copy the code from one event.ini to any future created event.ini. 

This way you can set it up for multiple monster types, and whatever is currently in use would activate the appropriate counter as it's eliminated. I hope this might provide some help, but like I said I'm still working on my Descent quest skills.

**Comment by Hobbeslionheart** [comment]
So I'm doing the Shadow Vault scenario from the Shadow Rune campaign. At the beginning of the Overlord turn, a monster is placed on the entrance as an reinforcement respecting group limits. The Overlord would know what group s/he has limits and would want to place the best tactically sound monster. In this situation, I randomize the monster group chosen for reinforcements; however, I say that if group limits are reached, choose another monster group to place. Well, the problem with this is the other monster group is defeated and is not spawned in the game, a monster will appear without a corresponding activation slot. 

So my solution was to simply prioritize the monster group when it was defeated so it would be reinforced the next turn or two turns if two monster groups were defeated. This would also up the difficulty then a master is spawned each time. Another solution could be to prompt the user to acknowledge when the monster group limit has been reached and have the group choose the other group which would be fine, but I could see this feature useful in other situations so thought having this ability to trigger based on the defeat of a randomized spawn would be useful.

**Comment by NPBruce** [comment]
Currently this is probably the best option:

Use the '#monsters' count to determine how many groups are out. Use defeated events to track the groups that are not open, and from there you can calculate how many open groups are deployed.

If both groups are deployed you could reinforce both or pick one at random or ask the user (no way around this).

If neither are deployed you can reinforce both or either based on whatever criteria is appropriate.

If one is delployed you can add them both with spawn events, but have text that says to reinforce the group that was defeated.

Alternatively, the RtL way to do this is just to alternate reinforcements each round, regardless of if limits are met.

I will add this as a feature request to think of a better way.

**Comment by BenRQ** [comment]
This has been described in details in #823.
This is a duplicate I think.

@delphiedie please reopen if required.
