### ISSUE TITLE
Multiple Items - re: #216

### ISSUE THREAD

**Issue by sodapaps** [NPBruce/valkyrie#597]
I've been working on a scenario for a while now, and during play testing I will sometimes get assigned the Whiskey item multiple times. I have it as a qitem that the investigators receive from one of the NPC's, but occasionally it will come up as a random item at either the starting items event, or at other, random qitem events. I can solve the problem by listing the whiskey as an item not to give during these random events, but I guess I assumed it wouldn't be assigned since it was one of my qitems. (And it is grayed out as an Item I can assign in the list.)

Thanks for all the work!

**Comment by NPBruce** [comment]
The only items that won't be selected on a randomized QItem are items that are already provided to the investigators.  If you want to prevent an item from being selected it must be specifically excluded.

This is because it is very hard to predict what series of events will cause which combinations of items to be available.  The grey on the list is purely a helper so you can see what has been used somewhere.

**Comment by sodapaps** [comment]
Thank you for the quick response. That makes sense.
