### ISSUE TITLE
Need Logo/Banner

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#6]
For pages, launcher and menu

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/tree/master/web

I have created a quick banner will leave this open until the app is updated to use it.

Still open to improvements.

**Comment by Sodiumbrella** [comment]
Hey, I have been thinking about making something for this for a while, and seeing your attempt inspired me to finally try it out. Sorry that you had to actually make something before I got myself together! Let me knowwhat you think and if you want to use them, I can make some proper files for you. 

![valk](https://cloud.githubusercontent.com/assets/21366798/22806344/f35df466-ef21-11e6-9a04-8eddadf2bff0.png)

**Comment by NPBruce** [comment]
This looks amazing!

Sytle-wise I like the first design, but it is a bit hard to read, so I would probably pick the second.

**Comment by NPBruce** [comment]
Another random nit-pick, when taking just the V+wing for an icon the line between the V and wing gets lost at low resolution.  Perhaps (at least in this case) changing the wing from black is a reasonable solution?

**Comment by NPBruce** [comment]
Musings:
![vicon](https://cloud.githubusercontent.com/assets/21050071/22808097/6862df86-ef7e-11e6-9e6e-36e9473fe235.png)

**Comment by Sodiumbrella** [comment]
Thanks :-)

I would tend to agree with you. I like the style of the first to sign better, but the second one is easy to read. And I see the problem and scaling it down. I was not really sold on just changing the color of the wing, so I tried making a version where the outline is thicker so that it's easy to see when scaled down. Of course, I couldn't really leave it at that, so taking some inspiration from Final Fantasy I tried playing around with colored gradients as well, to make it a little more interesting but also to help separate the wing from the V.

![valkyrie logo sheet v4](https://cloud.githubusercontent.com/assets/21366798/22825888/e260f1b8-ef8f-11e6-9629-598f095145af.png)

PS. Do you want the original SVG file?

**Comment by Sodiumbrella** [comment]
PPS. there is a white outline around some of them that you can't see because this file has transparency.

**Comment by NPBruce** [comment]
More amazing work.  I think I like the icon in the lower left best, and it works on black and while.  Are you happy with me using this?  Can you please make a banner that includes this wing? (doesn't need to have the same gap between the wing/v but the same gradient would be nice).

SVG files would be great also.

**Comment by Sodiumbrella** [comment]
Yep, I can make the banner. I will probably give the gradients another iteration, just to tweak it a bit, but I will keep the old version as well. How do you feel about the outlines? Personally I like them. Partly just because I like them visually but also because both the Descent and Mansions  (and Imperial Assault, sort of) logos also have outlines, so I like that symmetry, but you seem to gravitate more toward the versions without.

**Comment by NPBruce** [comment]
I like the black outline for the banner, don't mind either way for the icon.  I have release some images you have made in 0.5.7, I will revise them with whatever you come up with.

**Comment by Sodiumbrella** [comment]
Apparently, I am really bad at making decisions. I wanted to give you a "definitive version" but I kept changing my mind about which version that was. At the moment, I like the bottom version the best. The gradient is a little more subtle than in the original version. The logo on the bottom far right has a slightly thinner outline, which I felt worked a little better when I scaled it down in Inkscape, but it might not even be noticeable unless you make a direct comparison.

However, I'm a big fan of black and white aesthetics at the moment, and because your app is mostly black and white at the moment I can't help but feel that the white logo might actually work the best. Or, it might just be my indecisiveness playing tricks on me. I let that be up to you.

![valkyrie logo sheet v6](https://cloud.githubusercontent.com/assets/21366798/22883323/f7b7dd58-f1ef-11e6-9e76-cf51774fc760.png)

Also, I can't seem to upload SVG files in these comments. Is there somewhere else that I can upload it?

**Comment by NPBruce** [comment]
The top right icon works well enough scaled down, so I am OK with either the top row or the bottom row.  You clearly have better artistic ability than me, so I am happy for you to have the final say.

**Comment by NPBruce** [comment]
You should be able to use the web interface to add files to git (You may need to create a branch):
https://github.com/NPBruce/valkyrie/tree/master/web
I haven't done this myself though.  Otherwise you can upload it somewhere else and link.

**Comment by Sodiumbrella** [comment]
In that case I would go with the top one, the white one, at least as long as the app is mostly black and white as it is right now. I feel that one works as a complete logo right now, whereas the one with the gradient is lacking… something. 

I don’t really know how the whole branching thing works, but I will try to work it out and upload the file.

**Comment by Sodiumbrella** [comment]
Okay, I think I did it? Many apologies if I did something wrong.

**Comment by Sodiumbrella** [comment]
PS. The logo I uploaded has a slightly thinner outline, that I think works better when it is scaled down.

**Comment by NPBruce** [comment]
Pull request created here:
https://github.com/NPBruce/valkyrie/pull/40

I will leave this open until I have release a new version with the logo.

**Comment by NPBruce** [comment]
Released in 0.6.0
