### ISSUE TITLE
"Unable to locate Mansions of Madness, install via Steam" error even though it is installed on Windows 10

### ISSUE THREAD

**Issue by BoardgameMark** [NPBruce/valkyrie#615]
The title says it all.  I have MoM installed on my computer via steam already, but where I launch Valkyrie, it give me that message:
"Unable to locate Mansions of Madness, install via Steam"

Any help would be greatly appreciated.

**Comment by scrubbless** [comment]
Has the Official MoM app downloaded and installed? If you add it in Steam it wont always download and install right away. Check for it in your library and ensure its up to date.

I had this on a pc and found out although MoM was added to my library it had not been downloaded and installed (because id added it to my library on another decive first)

**Comment by BoardgameMark** [comment]
Wow!  Thanks for the speedy response.  I tried updating and it worked.  Thank you!  This software is amazing.  I'm buying MoM expansions because of it, and I hope to try my hand at a scenario when I find the time.  Thank you!
