### ISSUE TITLE
When Inspecting items, there is no default "Cancel" button

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#617]
If I create an event then link it as an "inspect" it does not act the same way as a normal event and give it a "Cancel button"

Event
![image](https://user-images.githubusercontent.com/32058089/31222720-05797aa4-a9c0-11e7-84bb-01519e21a01e.png)

Event Linked as Inspect
![image](https://user-images.githubusercontent.com/32058089/31222732-1213730a-a9c0-11e7-9617-cbbb247eb944.png)

How it looks in game, no Cancel button.
![image](https://user-images.githubusercontent.com/32058089/31222666-da92c390-a9bf-11e7-99a4-1bceeb8567b1.png)

**Comment by NPBruce** [comment]
To clarify a 'normal' event doesn't have a cancel button, only tokens do.  Because this gives you a bit more control, and mostly because changing it would break existing scenarios I am going to leave it like this until someone provides a reason to change it.

In your document you suggested that this behaviour isn't always the same though, which is an issue.  If that is true please reopen and explain.
