### ISSUE TITLE
Opening Downloaded Scenarios in editor

### ISSUE THREAD

**Issue by Kvothe-The-Bloodless** [NPBruce/valkyrie#647]
I wanted to ask: How do I open downloaded scenarios (such as the default The Fall of House Lynch) in the Editor? They don't show up there by default.

But while writing this question up and giving the matter one last thought myself I actually solved the issue. Still, I did not find it in the documentation ( I might have overlooked it though) so I just post this in case it might help someone else looking for an answer to this. (By the way, a FAQ type part for the documentation might be nice).

Solution:
When you download a scenario from the app it is downloaded to the \...\Appdata\Valkyrie\Download directory. (Type %appdata% into the explorer bar to go to the Appdata directory). The scenario file will have a .valkyrie extension but it will really just be a zip file. Copy it to \Valkyrie\MoM\Editor rename .valkyrie to .rar and unzip. 

Now it should appear in the editor.

**Comment by NPBruce** [comment]
There is a much easier way - use the copy function in the editor.  The copy will be editable.

**Comment by scrubbless** [comment]
I'll stick a section in my MoM guide regarding copying existing Scenario's, I didn't know this was possible. 

A separate note on this one, is content for any Scenario fair game to use assuming you reference any creators (listed in the authors of the original scenario). Or do we need to seek permissions from the people that created those Scenario's (i'd find that a bit odd, since we can freely edit their creations).

 There are some nice custom sound effects and images in some of the Scenario's that would be nice to re-use but I for one don't want to piss anyone off.

Anyway to address the topic. there is a lot of documentation regarding the Editor:
https://github.com/NPBruce/valkyrie/wiki/QuestGuideTutorials

Not sure an FAQ will be suitable, simply because there are so many complex topics to understand in Valkyrie, the list would look like a table of content.

**Comment by NPBruce** [comment]
> A separate note on this one, is content from any Scenario fair game to use assuming you reference any creators (listed in the authors of the original scenario). Or do we need to seek permissions from the people that created those Scenario's (i'd find that a bit odd, since we can freely edit their creations).

Being able to edit does not grand you a licence, just like any text or images on the internet.  Unless a licence is included in the package you will have to ask the author, by default everything (in life) gets copyright.  The only possible way around this is to force users to agree to terms that make their work CC licensed, but that is full of holes technically, annoying and probably not legally enforceable.  Note that many of the images and sounds in the distributed scenarios are reproduced under a permissive licence.
