### ISSUE TITLE
Is there a way to customize attacks on monsters, not monster attacks?

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#660]
I wan't a monster to be inmune to attacks until some condition is achieved. 
For this, I want to customize attack texts. One text for every type (spell, bladed,...).
Can this be done?

**Comment by scrubbless** [comment]
That's a cool idea, like having certain monsters take less damage from certain sources,

The only way I could think of doing it would be to drop it down with 999 health, then when the condition is met, remove the monster and put it down again. I have done something similar (much more health but still killable) in one of my scenarios.

Otherwise you could drop the monster with an event, rather than a spawn and use a token that has the monster icon. Then use EndRound events to move it around. The problem would be keeping track of it however.

**Comment by NPBruce** [comment]
There is currently no way to do this.
