### ISSUE TITLE
Save issues

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#699]
I don't think I've ever had a good experience with the "Save game" function.

The last couple of times I've saved a game, when I load the game I run into issue that I have seen several times, is that the "Menu" bars do not appear.

If you save a game and do a client upgrade, it is almost guaranteed to break the save, which is a bit of a shame.

I took a screenshot, but its on another device. Will update with it later.

**Comment by NicolaZee** [comment]
I agree the save game can sometimes be frustrating.
I find it can be helpful to frequently check valkyrie_Data\output_log,txt
All debug messages caught by the try...catch end up there.
So if things go wrong, there's a chance you may find some clue there.
I try to keep frequent backups - so I can roll back to a stable version when things do go completely pear shaped.

**Comment by redwolf2** [comment]
Most of the times saving is done using serialization techniques, which means writing the structured data of your live data objects to a file. This produces problems, when the structure changes, because a data object got bigger and needs more space or a naming has changed.
To get around that one has to write a custom serializer that can handle those structural changes, but that also need to be maintained.
Another approach would be to just save the savefiles sub dirs with the version name. That means that one a new version is out, the save files don't show up any more. This is the easy road, but could also lead to frustration on frequent version changes.

**Comment by scrubbless** [comment]
Maybe it could show "Greyed out" vX.X.X required, but not be clickable if the version is incorrect.

**Comment by NPBruce** [comment]
Please provide any save game file that does not work. There are no known issue with save games from 1.6 onwards. 1.5 and earlier saves did not work if there was an in progress puzzle.

**Comment by NPBruce** [comment]
I am closing this because there is nothing that can be done without a more specific case.
