### ISSUE TITLE
Android version 1.7.0b

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#701]
Runs really sluggish. Even simply loading up a scenario it gets slow to respond.

There are no performance options (like you get on the PC version). Is something that could be put into a pre-loading screen or an option in app?

It also crashes when you try to exit a large scenario, I assume thats linked to performance.

**Comment by redwolf2** [comment]
The Waittime at the start of a Scenario is mainly due to the Texture load time. He have no loading screen there, so the app just freezes for a Second, until the textures are there. 

Can you name the scenario, where the Scenario exit chrash happens?

**Comment by redwolf2** [comment]
I tested on the good old  Nexus 7 (2012) and can confirm the sluggish screen transition. 
There was no crash returning to the main menu. I would blame the crash to low memory and android crashing the application in some of those situations. If it happens to you again and is reproducable. Download catlog from the playstore and paste the log output here.

**Comment by NPBruce** [comment]
Does the official app run OK on the same system? If so it isn't a texture format issue. Perhaps the are some unity build settings to help with memory use, I doubt we are asking for more than the office app.

Otherwise if the official app doesn't run well it could be lack of hardware support for one of the encoding types. Perhaps we could transcoder, but I'm not sure it is worth the effort.

**Comment by redwolf2** [comment]
The official app runs ok in comparion. Maybe we can add a loading screen after the button "Start Scenario" and after the start of a scenario. Do the textues get preloaded or do they get loaded, when the tile shows up?

**Comment by NPBruce** [comment]
When the tile shows up.  So before you have started doing things it shouldn't use much memory.  If you go to the tile select window in the editor it will load all images (why it takes so long the first time).  This case doesn't matter too much - I can't see someone using the editor much on an old Android device.

**Comment by redwolf2** [comment]
Yes, I have seen that and don't worry about it too, but what about inside a scenario. Does opening a door loads the tile and the tile texture, or are all textures for the tile loaded on the start of a scenario?

**Comment by NPBruce** [comment]
Only when it needs to be displayed.

**Comment by redwolf2** [comment]
Can't we load all tile textures in at the start of the scenario? That may fix those small delays, when opening a door.

**Comment by NPBruce** [comment]
We could but it would take a long time to load the scenario.  Compromise position is start the scenario and background load all likely images after it has started.  Will use a bit more memory, but I think that will be OK (loading everything in the editor under Windows still stays under 2GB).

**Comment by redwolf2** [comment]
Everything is a trade off. So lazyload every texture in a thread. Priorize all visible tiles fist and then transition the textures in for example with a fade in animation.

**Comment by NPBruce** [comment]
It used to load them all up front and I changed it because I didn't like the long load time, don't want to go back (though we could also add a load screen).  Most load screens today exist for bad reasons.

This is a terminology detail, but we can't do threads in Unity.  The import uses another thread, but only because it doesn't call any Unity functions.  The work around is a 'coroutine' which Unity will call.  The problem is you need to manually break to resume the main thread, so we can do one texture per frame, but the frames will be pretty rough until all textures are loaded.

**Comment by redwolf2** [comment]
This helps a little bit:
https://github.com/NPBruce/valkyrie/pull/729

**Comment by redwolf2** [comment]
Maybe this is f*ing stupid, but I may try compressing the pvr files to pvr.gz, like mentioned here (at the end of the page):
http://wiki.sparrow-framework.org/manual/pvr_textures
My speculation is, that poor EMMC storage performance is leading to the bottleneck in the texture load. Deflate compression gets a texture to half the size. So we trade off CPU time to decompress, for faster IO performance. Will give a try.

**Comment by NPBruce** [comment]
Sounds plausible.  The official app doesn't do this, so I assume the load times will be the same (but that doesn't mean they are in the same place).

**Comment by redwolf2** [comment]
Most of the sluggishness was due to the auto save feature. This is fixed since version 2.1.0.
