### ISSUE TITLE
Some standard monster activations don't seem to make sense - D2E

### ISSUE THREAD

**Issue by ren6175** [NPBruce/valkyrie#747]
Hello,
As you said, the standard monsters should contain activations that follow the RTL activations. I am referring the list of actions that a monster group can take after being activated on any given turn. Usually, a monster will have 2-4 different actions listed for the player to cycle through (i.e. spot an enemy, attack closest enemy, engage an enemy within 5 spaces, etc.). However, when I created a quest (very basically) and spawned "barghests" they activation action options only list one action and it doesn't always make sense. I also tried with another monster "Lord Ferrow" just to see. His doesn't really make sense either. I'm not sure if it is a bug or if I'm just clueless and maybe that is how the program is supposed to work. The second option might be true.
![barghest2](https://user-images.githubusercontent.com/35081261/34549885-33fe1cde-f0da-11e7-9398-5b037b99ce4e.PNG)
![barghest3](https://user-images.githubusercontent.com/35081261/34549886-340b5fd4-f0da-11e7-9cda-a7629f71de2e.PNG)
![lmferrow1](https://user-images.githubusercontent.com/35081261/34549887-3418126a-f0da-11e7-85ae-2a70006d282f.PNG)
![barghest1](https://user-images.githubusercontent.com/35081261/34549888-34248450-f0da-11e7-83ac-7b59c511241d.PNG)

Thanks again,
Dave

**Comment by DelphiDie** [comment]
I think this is due to the way, the texts are imported from RtL and stored in the localization_en.txt. 

Here is an example:

```
BARGHEST,"Barghest"
PLURAL_BARGHEST,"Barghests"
INSTRUCTION_BARGHEST,"Barghests spend ± in the following order: \n ±: +X ≥"

EFFECT_BARGHEST_1,"Each hero who suffers 1 ∏ from ""Howl"" also suffers 1 ≥."
BARGHEST_1_MINION_0,"∞ Spot as many heroes as possible.
∞ Use ""Howl"" on at least 2 heroes."
BARGHEST_1_MASTER_0,"∞ Spot the closest hero.
∞ Use ""Howl"" on at least 1 hero."

**EFFECT_BARGHEST_2,"""Howl"" affects heroes within 6 spaces instead of 3 spaces."**
BARGHEST_2_MINION_0,"∞ Attack a hero.
∞ Use ""Howl"" on at least 1 hero.
∞ Spot as many heroes as possible."
**BARGHEST_2_MASTER_0,"∞ Engage the closest hero.**
∞ Use ""Howl"" on at least 1 hero."

EFFECT_BARGHEST_3,"Each hero who is adjacent to a Barghest and suffers 1 ∏ from ""Howl"" also suffers 2 ≥."
BARGHEST_3_MINION_0,"∞ Engage a hero who is not adjacent to another Barghest.
∞ Use ""Howl"" on at least 1 hero."
BARGHEST_3_MASTER_0,"∞ Spot as many heroes as possible.
∞ Use ""Howl"" on at least 1 hero."
```

It seems only the actions which are in the same line as a KEYWORD are actually used for the activation. I highlighted the activation from your example.

This might also happen for custom monster activations in some quests. Example:

```
SOC_Q_MIA_ZOMBIE_ACTIVATION_MINION,"∞ Engage the closest prisoner.
∞ Attack the adjacent hero with the lowest π."
SOC_Q_MIA_ZOMBIE_ACTIVATION_MASTER,"∞ Engage the closest prisoner.
∞ Attack the adjacent hero with the lowest π.
∞ Use Grab"" on the adjacent hero with the lowest ∂."""

Another instance of this behavior are texts which contain multiple bullet points. Example:

```
PRODUCT_DJ01_TITLE,"Descent: Journeys in the Dark"
PRODUCT_DJ01_DESCRIPTION,"As the essential core experience, the [i]Descent: Journeys in the Dark Second Edition[/i] base game provides the heroes with everything they need to begin a [i]Road to Legend[/i] campaign."
PRODUCT_DJ01_CONTENTS,"Digital content unlocked:\n
**• 8 heroes
• 9 monster groups
• 8 hero classes
• 34 shop items
• 4 conditions
• 8 side quests
• 20 stages for [i]The Delve[/i]
• 4 map variants for [i]Trials of Frostgate[/i]"**
```
```

The values marked in bold should all be in the same row as PRODUCT_DJ01_CONTENTS.

**Comment by mickkn** [comment]
Is there anyway to fix this?

**Comment by NPBruce** [comment]
Fixed for next release.
