### ISSUE TITLE
Question on conversations (token/event issue)

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#752]
Hi,

I have a question on making conversations with NPC in MoM. First, I will describe my intend:

I have a token of some NPC. I make a button "asking 1" and assign "answer 1". I want after this allow to player click on the token again and have possibility to "asking 2" with "answer 2" and also "asking 3" with "answer 3". After the player use the button "asking 2" and again click to that same token, he will see only the possibility "asking 3". And of course, the same with first hitting button "asking 3" and then have the possibility to click on "asking 2" later.

So far I solve my problem with more tokens of the same person with different opportunity and a lot of vars and everytime some conversation event is started, I remove one token and I add another (still the same picture but another text and/or buttons). It is very annoying to have so many tokens of the same person.

Here is my question: Can I do this with some elegant simply way? For example, when I hit button with "asking 2", next time it will not be there?

**Comment by scrubbless** [comment]
You do not need to keep replacing the token.

Create the one token and a button. Put in no dialog.

Then create events for each question and set the token to 'ordered' (or random if you want).

Open the first event and set a test. Question1 != 1.

This event will only show when the Question1 variable is not set to 1. 

At the end of the dialog assign the variable Question1 = 1.

Repeat this for all of your questions.

When you click the token it will pick in order (or at random if you set it) a question event. But will not pick the same question more than once.

Create an event at the end as a catch all. That has a test:

Question1 = 1
Question2 = 1
Etc

Then have this event say something and remove the token (or not).

You can be clever here and have questions unlocked by other events. But I'll go more into that as a topic on my MoM guide :)

**Comment by scrubbless** [comment]
I'll will link the guide when I have time at a PC to write it up!

**Comment by FASTNAVi** [comment]
Thank you for response. I read your guide of course ;-) But I have slighty different issue. I need different text on button for each question.. I can do that you are describing (ignoring some event, when var is set right) but I need different button whit different "asking" sentences..

For example:
"How are you?"
"How much cost this?"
"Which time is now?"

And when I choose one, the button will not be there next time and rest of them stay. Do you understand my problem now? :)

**Comment by scrubbless** [comment]
You can use the process above. 
With no dialog when you click the token it picks and runs the event, without showing anything.

Each "question"  event can have its own question buttons. It's too complicated to explain here, so I'll try and write up an example of exactly what you are looking for :)

**Comment by scrubbless** [comment]
Too complicated for me to explain without pictures is what I meant. But what you want is completely possible.

**Comment by FASTNAVi** [comment]
Well.. I don't know how to run event without button on setting of token. I will wait for more complex advice from you. And thank you for your time! This issue is something what really miss me in your guide.

**Comment by scrubbless** [comment]
It is something that I only really came up with after writing the guide. It was on my list to add, after I finish my next scenario. But will always respond to specific needs/questions!

**Comment by scrubbless** [comment]
I have done this in one of my Scenarios, but i'll run you throught it now in an example and upload the example scenario.
I touch on it in this section, but you need to extrapolate it out to get what you want:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.xz3hn391u18p

So we start off with an event to place our guy:
![image](https://user-images.githubusercontent.com/32058089/34799977-d64aba5e-f659-11e7-9998-b0e4b9b18529.png)

In the token we do not add any dialog at all. We just create events for each set of options. You need an event for each possible variable of questions, I have used online permutations calculators in the past to work out what I need.

So in your example we need events for every possibility of:
Talk - How are you?
Cost - What is the cost?
Time - What is the time?

These are (forgive me if I get it wrong, its late!) 7 permutations, then we need another "catch all".
1 - Talk, Cost, Time
2 - Talk, Time
3 - Cost, Time
4- Talk, Cost
5 - Talk
6 - Cost
7 - Time 
8 - No questions - catch all.

We need an event for each of these 7 permutations + 1 catch all (8 events):
![image](https://user-images.githubusercontent.com/32058089/34800404-7803d852-f65b-11e7-8dcc-9d5a4459f54e.png)

Notice that the token has no dialog. This means it will pick one of those talking points. Because it is set to "Ordered" it will go down the list one at a time.

Now we need to set up the events with their questions, and set Variables to hide them.

So the first event - Talk, Cost, Time (all questions)
I set a test on the event that checks  a variable for each question, if they are all not = to 1, it will run.
![image](https://user-images.githubusercontent.com/32058089/34800513-0b0bac4c-f65c-11e7-944f-d8fff57e7520.png)
![image](https://user-images.githubusercontent.com/32058089/34800539-2b2fe772-f65c-11e7-9181-87a86446212e.png)

So the first time we run it, we should expect to see this event.

We repeat the process for the next event, this time we are only asking 2 questions:

Talk, Time 

(The idea being, that the cost question has already been asked).
- I forgot to mention, in these events the "Cancel" button is not automatically added like the Tokens are, so you have to add it yourself. Just add another button called "Cancel" with no event, this will exit the event if the player clicks it.

So here is what that event will look like:
![image](https://user-images.githubusercontent.com/32058089/34800703-e59391ae-f65c-11e7-8a6b-0c076b918126.png)
Notice I have highlighted a variable. Because we are assuming "Asking the cost" has been done, we only want to show this event, if the variable has been set (this will become clear in a moment). The questioned asked are exactly the same as the variables that have != 1 next to them.

Here is how the rest will look:
Cost & Time 
![image](https://user-images.githubusercontent.com/32058089/34800831-801c7bb4-f65d-11e7-8c71-93593d03e54e.png)

Talk & Cost
![image](https://user-images.githubusercontent.com/32058089/34800897-bc9438f2-f65d-11e7-8c71-b443a3fd8dc0.png)

Talk Only
![image](https://user-images.githubusercontent.com/32058089/34800935-dfe19fb6-f65d-11e7-9799-c99e001c9c26.png)

Cost only
![image](https://user-images.githubusercontent.com/32058089/34800961-03db8f76-f65e-11e7-84e5-30c3e91d7c3c.png)

Time Only
![image](https://user-images.githubusercontent.com/32058089/34800990-21a815c4-f65e-11e7-8929-8f5ccff813ee.png)

Ok now we have all of our questions ready, we need to make the events that are triggered by the question, then flag the variables (Trader_*** = 1) for each one.

So lets do them one at a time, I will do this from the start event (Talk, Cost, Time):

I have created an event for each question, these same events will be used in every permutation event:
![image](https://user-images.githubusercontent.com/32058089/34801049-6643d286-f65e-11e7-9122-6257972ef0a9.png)

So one for the answer to "Talk":
![image](https://user-images.githubusercontent.com/32058089/34801056-734e9c68-f65e-11e7-8cbb-8b37dbf47268.png)
We put in the dialog, from the man (I would do it as a series of event usually. But one is fine for this example).
Then we flag the variable "Trader_Talk = 1"

This variable signifies that we have talked to the trader, and when we click the trader token the next time, the talk options will not trigger.

Now one for the answer to "Cost":
![image](https://user-images.githubusercontent.com/32058089/34801119-ce5a6cae-f65e-11e7-9a9f-c5d2c11647a1.png)
Same process.


Now one for the answer to "Time":
![image](https://user-images.githubusercontent.com/32058089/34801136-e0759044-f65e-11e7-8a98-d8d0957d787d.png)

Go through all of the events and fill in the events under the corresponding questions:
![image](https://user-images.githubusercontent.com/32058089/34801159-063fcda8-f65f-11e7-93d1-d1f3c9bc17ec.png)

Here is an example of the second one, im sure you can figure out the rest!
![image](https://user-images.githubusercontent.com/32058089/34801152-f21946ce-f65e-11e7-9c29-9e0be416301a.png)

Finally create that catch all event, this should be at the bottom of the list:
![image](https://user-images.githubusercontent.com/32058089/34801174-27685036-f65f-11e7-8e74-f8ada5033471.png)

Don't give it any variables, so it will always trigger if all of the above 3 variables get set to 1 (Trader_Talk/Cost/Time). In my example this event will also remove the trader person:
![image](https://user-images.githubusercontent.com/32058089/34801191-46151e42-f65f-11e7-8034-0e3d78ca84b7.png)



Ok so lets run it and see the fruits of our labour!

Start game, trader is placed:
![image](https://user-images.githubusercontent.com/32058089/34801214-5f750c8a-f65f-11e7-95ee-714f7cdbe9f1.png)
![image](https://user-images.githubusercontent.com/32058089/34801221-68907390-f65f-11e7-807a-2e823f251f44.png)

We click the trader. Here are my variables:

Trader_Talk = 0
Trader_Cost = 0
Trader_Time = 0

(you can check variables by clicking the log if you've done a"save&test" or clicking log and then pressing Alt+d (I think, or is it Ctrl+d? Try both!)
![image](https://user-images.githubusercontent.com/32058089/34801265-a2a420d6-f65f-11e7-9ecf-ae38b6483012.png)
As you can see we have all 3 questions! Good start.

We we click and ask about the "Cost".
![image](https://user-images.githubusercontent.com/32058089/34801290-c646bf12-f65f-11e7-9373-9cd1cc09402f.png)

Now we re-click the person, and we should expect the variables to be:

Trader_Talk = 0
Trader_Cost = 1
Trader_Time = 0

![image](https://user-images.githubusercontent.com/32058089/34801296-ce3229d2-f65f-11e7-9b8b-5e943ffdff82.png)
Boom, the "Cost" question is no longer there! 

So we click on "Time" worried that we don't have time to finish talking to this guy (but of course we don't intent to buy from a crazy man running into a mansion to sell bolts!?!).
![image](https://user-images.githubusercontent.com/32058089/34801315-f6f5bd66-f65f-11e7-972b-7009dcc2ac77.png)

So we click on the trader again, we expect the variables to be:
Trader_Talk = 0
Trader_Cost = 1
Trader_Time = 1

![image](https://user-images.githubusercontent.com/32058089/34801331-0e6c9438-f660-11e7-8ac3-f0ba414e3d94.png)

Nice, so we got what we expected. We ask him how he is!
![image](https://user-images.githubusercontent.com/32058089/34801343-1e1cdd84-f660-11e7-9972-9337c10ce889.png)

At this point, I might consider putting an event after all three of the "TraderDIALOG_/Cost_Used/Time_Used/Talk_Used, which trigger the no dialog option. This would run after the final question was asked, and remove the token. But I haven't here. 

So we click on the token again, expecting the variables to be:

Trader_Talk = 1
Trader_Cost = 1
Trader_Time = 1

All questions gone, so we should expect to see the "No Options" dialog and remove the guy.

![image](https://user-images.githubusercontent.com/32058089/34801410-79ee1b6e-f660-11e7-9c3c-527c3a03c47d.png)
And there, he goes. Crazy bolt sales man.


I hope this was of help, I will add it to the guide tomorrow or friday :)

Have a nice evening, and good luck with your scenario!

**Comment by FASTNAVi** [comment]
Hey! Thank you so much. This is really helpful! You solved my problem. I don't realize, that token with no text window AND with button will work. Right now it is really simply.

But I let a several persons in my scenario in "old" my style.. you know, too much time spent to making them right :D I did them my own difficult way and it was working but your way is much more better.. so next time =)

One more time, thank you very much for your time! My scenario will come soon (about 3 weeks from now).

Good night to you too!

**Comment by scrubbless** [comment]
I did it the same way as you last time. I only figured this one out writing my most recent scenario. I will check the guide to make sure I don't lead people astray in the future.
