### ISSUE TITLE
Is there an updated tutorial for Descent?

### ISSUE THREAD

**Issue by eternaldreamon** [NPBruce/valkyrie#776]
Hey all!  I have been playing around in Valkyrie for a little bit for Descent.  I tried to follow the short tutorial as much as I could, but a lot of the information was wrong.  I think it must have been written from a previous version.  I'm still playing around in it and trying to figure out how to work it.  I was wondering if there has been any other updated tutorial made?  At least I'd like to know some of the inner workings of the program.  If there isn't one, I have some questions if someone can help me out.

So I'm trying to translate quests from the Shadow Rune to Valkyrie.  I see someone already started the project, but I wanted to try for myself for practice.  So I can make the first quest just fine.  I have a good grasp of events and how they flow into each other.  Once the first quest is completed, I want to figure out how to go to a campaign screen.  Ideally I'd like to have the picture of the map of the Shadow Rune shown, and with little buttons of places you can go for quests.  It looks like the map picture and quest pictures for the map are labeled under UI I think.  When I select it it just blows it up to the whole screen.  I can't drag and drop the quest buttons on the map, and instead have to align them with X and Y coordinates.  I'd like to be able to just move them like I can tiles, and arrange them in order however I want.  Is this even possible?

Second, I think I saw something about flags where you can specify certain numbers.  I haven't really figure that out yet.  Pretty much I program each event to flow into another.  It would be nice to be able to set off flags that would tell you which quests you completed and such.  Imagine if you could do the Shadow Rune campaign and it would allow you to pick 3 of the initial quests.  After the 3rd one, it would immediately transition you to the Interlude, which would be different whether you won or lost more of those 3 quests.  Then it will know which of the 5 Act 2 quests to let you play after that.  Is something like this even possible in the program?

I guess those are the big two questions right now.  Anyway, thanks for your time reading this.

**Comment by NPBruce** [comment]
I have updated the tutorial found here:

https://github.com/NPBruce/valkyrie/wiki/QuestCreationTutorial

For campaigns I strongly recommend downloading and trying the "Valkyrie 1.1 Feature Demo", it should do everything you want.  You can make a copy using the editor, then you will be able to edit it yourself to suit your needs.

As for your conditional events, you can do all of that.  Anything you want to track you can add to a var in any event.  This is done with operations, see here:

https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#operations

If your variable starts with '%' it will last for the whole campaign, otherwise it will be cleared at the end of the quest.

Anywhere you want to change what happens based on a var you use a condition:

https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#conditions

Each button from an event can have any number of events linked to it.  It will work through the list until it finds an event that has the conditions met.  This might look like this:

EventEndQuest
 - Continue Events:
   - EventWon
   - EventLost

EventWon
 - Condition varWon == 1

**Comment by eternaldreamon** [comment]
Thanks for the reply.  I'll definitely look into all of that.  Can you give me a link to download the Valkyrie 1.1 Feature Demo you mentioned?  I can't figure out how to get it.  I've searched google but it just gives me pages on here with files, no download link I can find.  Maybe I'm just incompetent.  XD

**Comment by scrubbless** [comment]
I wrote an in depth tutorial for MoM, but I have not used it myself.

However I suspect bits overlap. The campaign part of descent just looks like layering UI components, treasure is laying tokens, monsters look similar to spawns.  Doors work slightly differently than they do in MoM.
I've not got round to creating a quest for descent yet. But when I do I'll write up a similar tutorial (or if it's similar to MoMs, I'll add sections for descent to the existing MoM guide).

Feel free to check it out here:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/

**Comment by NPBruce** [comment]
Closing as the quetions have been answered.
