### ISSUE TITLE
 “Silent update”

### ISSUE THREAD

**Issue by Gruszkin** [NPBruce/valkyrie#824]
### Description of Problem or Question

how to update a token if it is not already on the board. I mean, after discovering the token "?" I would like another token that is not already on the board to be updated, that is, to drop off and a new updated token will wait instead.

I mean this situation. Seekers discover the token "?" In which the text reveals to them that in the kitchen they have not yet discovered, they will faund a  secret passage. How to do it, so that when they enter the kitchen, by reading this information, a  token appears with the passage and when this information is not available, the secret passage will not appear.
i use google translator :(
### Valkyrie Version

2.0.1

**Comment by scrubbless** [comment]
You don't have to put text in a token. Instead just put two (or more) events under the button.

If the button order is "ordered" it will play the first event. In the event then out in a 'Test' to check a variable. 

E.g. <Variable 2 == 1>

Then make the second event the default 'first event's.

Use Assign in an event to 'turn on the second event' 

Assign:
<Variable2 = 1>

**Comment by Gruszkin** [comment]
Ok, I understand it a little more. It is not easy to understand all of this right away. I have one more question
![1](https://user-images.githubusercontent.com/38963091/39677099-cb846864-5175-11e8-8a14-3b10001a5649.JPG)
players reach this token. Activates this event "Event92"

I would like that from this moment, only this myth would run every turn
![2](https://user-images.githubusercontent.com/38963091/39677133-594ff528-5176-11e8-950c-0fc3f5a2036b.JPG)

if it is like a myth in the picture, it works every turn from the very beginning. 

How to set this myth to work only from this specific point

**Comment by scrubbless** [comment]
In the special mythos event 97? you can add a test that checks for a variable (variable == 1). In your other mythos events 92 put a test that checks the same variable 'is not equal to' (variable != 1).

Then in the event where you interact with the door, use Assign to set 'variable' to 1 (variable = 1).

Event92 will run every mythos phase because 'variable' is 0. When the player opens the door the  'variable' is now 1. So Event92 can no longer run, but Event97 can now run instead.

Hope this makes sense.

StartRound, EndRound and Mythos event triggers are all work the same way, just happen at different times in the round.
