### ISSUE TITLE
Question - Campaign Screen / link external quests/Scenarios

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#839]
[###](url) Description of Problem or Question
Hi all,

I was considering looking into making a campaign mode for either a descent campaign, or mansions of madness. However I am curious how it works.

Would I create one quest as the campaign, then reference a second quest (aka a side mission or campaign mission) from there. Can I track variables between campaign missions.

Is there a tutorial for this anywhere?

**Comment by NPBruce** [comment]
That is exactly how it works.  There is an example available for D2E, but it would work the same under MoM, take a look here:
https://github.com/NPBruce/valkyrie-questdata/tree/master/source/D2E/campaign

Currently you can't link the quests in the editor, this has to be done manually.

The example above has the 'campaign' quest at the root level, and then other quests inside it. When creating a package all quests in subdirectories will be included. If you don't want the quests to be started directly you can set them to hidden (like this - can be done in editor: https://github.com/NPBruce/valkyrie-questdata/blob/master/source/D2E/campaign/q1e2/quest.ini).

To link quests have an event which points to a quest.ini file rather than another event like this (UIStart):
https://github.com/NPBruce/valkyrie-questdata/blob/master/source/D2E/campaign/ui.ini

**Comment by scrubbless** [comment]
Thanks Bruce! I was considering a campaign mode that has story mode and  and uses existing scenarios as side quests. 

Is it possible to link a 3rd party scenario (assuming I have the authors consent).

**Comment by NPBruce** [comment]
It is, but you need the relative path. There is no way to search for it, if it was installed as a package in the same way then it should work, but future compatibility would be near impossible to control anyway.

I'd suggest packaging a version of the scenario (even if it is the same) with the campaign, in order to maintain control over the interactions.

**Comment by scrubbless** [comment]
Thanks @NPBruce , I get it now. I thought it was something we had to do manually in the quest.ini but I was not exactly sure how. This is perfect!
