### ISSUE TITLE
Accessing the text in the MoM Import Folder Text File

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#872]
There is a lot of useful text in the FFG localization text file in Mom\import\text.
For example the following text is used in every scenario  "EXPLORE_MOVE,You may move 1 space into the explored area."

Is there any way of referencing such text item from a Valkyrie MoM Scenario?
If not, please can this functionality be added.
e.g. like {MoMImport:EXPLORE_MOVE} would automatically reference EXPLORE_MOVE from the appropriate language import text file.

It would make translating scenarios into different languages easier.

**Comment by NPBruce** [comment]
I don't want to directly expose the FFG text, because it could change, specifically how it is referenced and if some parts of it are arguments.

I could make exceptions on a case by case basis, but you might be better off just copying the text you want into your scenario, and referencing it that way.

**Comment by NicolaZee** [comment]
OK it's your call.
:)

I'll close the issue.
