### ISSUE TITLE
New user. Trouble with many things

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#937]
### Description of Problem or Question: 

Problem N°1: When copying a scenario to use it with scenario editor all attempts crashes.

Problem N°2 Cant seem to find how to avoid getting a loop with first round mythos phase and starting all from beggingn upon returning to investigator phase. 

Problem N°3 Cant find a way 

### Valkyrie Version
2.1.2

**Comment by BenRQ** [comment]
Hi

> Problem N°1: When copying a scenario to use it with scenario editor all attempts crashes.

it's a known issue ( #936 ), will be fixed in next release 

> Problem N°2 Cant seem to find how to avoid getting a loop with first round mythos phase and starting all from beggingn upon returning to investigator phase.

The tutorial from @scrubbless is a good start for scenario creation.
You should have a look at it : 
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8

> Problem N°3 Cant find a way

Please pick a madness card now ^^
![image](https://user-images.githubusercontent.com/40794717/47609378-88560880-da3d-11e8-83d5-f069ef918f77.png)

**Comment by newusergettingnuts** [comment]
:) great, many thanks

So problem n° 1 solved (get a clue token)
Problem N° 2 i guess i solved it too..the structure so far goes like....QUEST....EVENT TO SHOW UI PROLOG (IMAGE, TEXT AND CONTINUE BUTTOM THAT LINKS TO FIRST TILE, TOKENS, etc. 
 
Already placed also first mythos...structure goes like this...rename Mitos round 1....insert dialog (will test 2 or suffer 1 horror facedown)....trigger mhytos....assign button: mythos flavour=0....insert .button none.

I am not sure how to add a second mythos without appearing in the same mythos phase

:(

still tinkering

**Comment by newusergettingnuts** [comment]
well i cant seem to get it done..i am sharing an image of both mythos events so if anyone knows how to make them appear ordered will help a lot 

<a href="https://ibb.co/kwyqLq"><img src="https://preview.ibb.co/mTYPfq/Mythos.png" alt="Mythos" border="0"></a>

**Comment by scrubbless** [comment]
I'll give this a better read tomorrow and respond. 

For you insight, 'mythos' trigged events will always run. I think it's random in which order they are picked.

Personally I use one event and put the mythos trigger on it. The event is left empty and then chain i events from it, using a 'test' on each event to indocate if it is 'on' or 'off'.

This way you know your triggered mythos event will always run. But you are in control of what event it runs and in what order.

If you turn off normal mythos events your need to turn them back on at endround or start round. You can't do it during the mythos otherwise it'll trigger after your event finishes.

**Comment by newusergettingnuts** [comment]
Many thanks benrq and scrubbles! Get a clue token each! {action} Can close the issue if you have the key item :)

![image](https://user-images.githubusercontent.com/44534194/47623859-d417b900-daf4-11e8-875c-226469d9d696.png)

Problem N°1: Solved exporte de zip file and manually located it in the MOM editor file

Problem N°2 Solved, finally used one event for each mythos phase.-

trigger: Mythos
Button: Continue 
Test: #round==1  this order assign the mythos to round one...so if i put 2 it appears in round 2 and so on.

![image](https://user-images.githubusercontent.com/44534194/47623795-112f7b80-daf4-11e8-9452-7e94db77326c.png)

**Comment by BenRQ** [comment]
Happy to help  👍 

Join us on Discord if you want to chat :)
https://discord.gg/yrVeSVt

**Comment by scrubbless** [comment]
Yeh, always happy to help :)
