### ISSUE TITLE
Editor Quirks - Enhancement

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#970]
### Description of Problem or Question
The {Number} for variables, {New UI} for UI and {New Token} for Tokens - no longer pin to the top when sorting. Its fine for events, puzzles and spawns.
![image](https://user-images.githubusercontent.com/32058089/49367175-301cc100-f6e3-11e8-900e-0e42ff386860.png)
![image](https://user-images.githubusercontent.com/32058089/49367330-b0dbbd00-f6e3-11e8-99ec-761be01e16fe.png)
![image](https://user-images.githubusercontent.com/32058089/49367378-cea92200-f6e3-11e8-9028-18f95ec42294.png)

Could you make each of the menu's sorted and unsorted either Left aligned or center middle aligned (I prefer left aligned personally)
![image](https://user-images.githubusercontent.com/32058089/49367190-3ad75600-f6e3-11e8-8554-b23a12c63ac0.png)

### Valkyrie Version
2.1.4

**Comment by antontimmermans** [comment]
Another editor enhancement could be to condens and reorderd the input fields a bit so that it doesn't contain so much black space (especially in the top part) so you have a better overview your event. Example: (note i moved the triger field up)
![condensed event](https://user-images.githubusercontent.com/42072372/49435668-6f1c4680-f7b7-11e8-88c6-b682d437002b.png)

or token editor:
![condensed token](https://user-images.githubusercontent.com/42072372/49435690-7ba09f00-f7b7-11e8-929a-8ddc986409df.png)

Or do you want this in a separate ticket?

**Comment by scrubbless** [comment]
Don't see why it needs to be more than one :grin:

I just noticed that the stacking puzzle text is in Chinese! (I had english selected)
![image](https://user-images.githubusercontent.com/32058089/49454998-43608700-f7de-11e8-81e2-1482058c4681.png)

**Comment by BenRQ** [comment]
I would prefer 3 issues for those 3 different topics :)
Easier to manage!

@scrubbless for your request for ordering, it is already left aligned for alphabetical order and center for sequence order.
What would you expect there ?

**Comment by scrubbless** [comment]
Hi @benrq, I'd like it all either center aligned or all left aligned. My preference being all left aligned.

**Comment by BenRQ** [comment]
Also please note that all component always start by {new XXX} if sorted by number.
So I guess your request is also to keep the {new XXX} even if sorted by alphabetical order.

**Comment by scrubbless** [comment]
Yeh, they should be pinned regardless of how the lists are sorted

**Comment by mayjak** [comment]
Always on top ordering for special editor variables is fixed in 2.5
