### ISSUE TITLE
New Scenario - OResgateSombrio

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#991]
Afternoon gents, there we go
https://github.com/andrex47/MOM2-OResgateSombrio

**Comment by scrubbless** [comment]
Added, did you know you can add a scenario image? On the quest screen there is a place to select an image. Just drop a jpg or PNG in %appdata%\Valkyrie\MoM\Editor\<scenario name>\ then it will show in the images list.

**Comment by scrubbless** [comment]
I don't speak French, however when running the scenario I can see a few issues.

I would be happy to help polish the scenario (and translate to English after if you like).

Some examples of improvements.

The scenario does not have an image.

All tokens have continue and cancel dialogue, then a follow on event to see if it's usable. This could be done with a single dialogue/event.

When the game ends it doesn't remove the monsters that are in play.

When you finish the scenario (I assume by running out of the door) it doesnt end the scenario (assign $end = 1) therefore the review page will not display.

**Comment by andrex47** [comment]
thanks i will check it and update the file

**Comment by chrismaliszewski** [comment]
Hi. Some things to improve. First of all, I don't speak Portuguese so I was not able to follow the plot. Second, I tried any paths leading to different endings.
So:
-(PLOT), isn't that a bad idea, to allow players to start in a room where they can wander around but do nothing more than begin a dialogue? It'd be better if there was some kind of blockade so they don't waste their time and go straight to the point,
-(PLOT) why the toilet is open and empty if in the next moment it's not? It'd be good to shut the door, too. Additionally, that makes sense after you defeat the enemy so, as a result, you won't be getting any other item from the place. Especially since the event token suggests it's an important item (so it's not?). I suggest changing the token to a question-mark one,
-(PLOT) it is VERY bad to punish a player for being curious about what is behind the next corner. What I mean is, if a player goes to the top left room before having the required items, the game punishes the player and blocks possibility to obtain a specific ending. It'd be good to allow a player to forfeit the action if he/she is not sure to open the door being afraid that not having a required item may do sth bad,
-(BUG) The item found in the toilet after interacting with the token has a wrong name; c:Qitem7 name shows up instead,
-(MISTAKE) after Investigators are moved to the bathroom and you interact with the event token, there is 2 line text ("Tentar cortar"); it'd be good if it was 1-line text,
-(ENHANCE) I think there isn't any test that has a failure text. It'd be nice if they had, all of them,
-(ENHANCE) Add more descriptions, i.e. obtaining items etc.
-(BUG) Monsters stay on the board after spawning (and defeating) in the top left room,
-(MAJOR BUG) After clicking 'Sair' on the main door, nothing happens: reveal a blue man, talk with him until he disappears (doesn't matter what option you choose), open the door at the top left, choose No, interact with the main door and choose Sair (nothing!),
-(BUG?) Not sure if a bug, after interacting with the main door, it is possible to respawn the guy over and over again and it resets the riddle's state. Remove possibility to respawn the guy,
-(ENHANCE) Is it me, or the tower riddle is FAR FAR TOO difficult! Change a riddle type,
-(BUG) If Investigators don't have 3 grotesques statues and go into the attic, the game doesn't have an ending.

**Comment by andrex47** [comment]
thanks everyone for the feedback, i will give up this scenario, i'm not the author, i just found it in the brazilian version of boardgamegeek.com that is called ludopedia.com.br and then asked if the author would allow me to publish it, so i did it, i published it, in the last email i sent the author about the erros you guys found he told me he doesn't have the time to deal with the scenario right now, so i guess this scenario is gone for good, i just wanted to allow more people to play it XD

**Comment by andrex47** [comment]
the only thing i can do about this scenario is translate it to english, if someone would give it a chance to make corrections so be it it would be awesome, of course, i will ask the author if he wants to allow people to enhance his scenario

**Comment by andrex47** [comment]
the author authorized us do fix the scenario, i will begin translating at once

**Comment by chrismaliszewski** [comment]
I'll provide a Polish translation today as well as help with new ideas and testing.

**Comment by andrex47** [comment]
thanks a lot @chrismaliszewski, the english translation is also ready @scrubbless

**Comment by scrubbless** [comment]
Could you give me collaborator permissions? I'd rather branch and work on the scenario on your Repo than work independently on a version only for someone else to translate or modify this version.

**Comment by andrex47** [comment]
added

**Comment by redwolf2** [comment]
I will close this for now. Y'all can always continue the discussion even on closed requests, create a new issue or ask for reopen.

**Comment by vidimus** [comment]
> Here is a link to Polish translation [https://drive.google.com/open?id=1OhU4yO7Fz9AntbVcD8_rwX1RmYotJmV7](url). I'm eager to help with other things if needed.

Did this translation ever go online?
